core/CHANGES.txt, core/src/zeit/cms/checkout/tests/test_webhook.py, core/src/zeit/cms/checkout/webhook.py, core/src/zeit/cms/testing.py
Needs https://github.com/ZeitOnline/vivi-deployment/pull/71
=> IR-59: Allow configuring excludes for checkin webhook

core/CHANGES.txt, core/src/zeit/content/cp/automatic.py, core/src/zeit/content/cp/blocks/configure.zcml, core/src/zeit/content/cp/blocks/rss.py, core/src/zeit/content/cp/configure.zcml, core/src/zeit/content/cp/tests/test_automatic.py
Also includes a minor refactoring.
=> BUG-1121: Enable RSS-Teaser objects as lead candidate

core/setup.py
=> ZON-5595: Loosen version requirements for gocept.fckeditor

core/CHANGES.txt, core/setup.py, core/src/zeit/cms/browser/skin.zcml, core/src/zeit/cms/ui.zcml, core/src/zeit/content/image/browser/README.txt, core/src/zeit/content/image/browser/configure.zcml, core/src/zeit/content/image/browser/image.py
=> ZON-5590: remove all occurrences of z3c.conditionalviews

core/setup.py, core/src/zeit/cms/browser/listing.py, core/src/zeit/cms/browser/login.py, core/src/zeit/cms/browser/tests/test_login.py, core/src/zeit/cms/browser/widget.txt, core/src/zeit/cms/checkout/browser/README.txt, core/src/zeit/cms/cmscontent.txt, core/src/zeit/cms/configure.zcml, core/src/zeit/cms/content/browser/widget.txt, core/src/zeit/cms/content/field.py, core/src/zeit/cms/content/reference.py, core/src/zeit/cms/content/tests/test_add.py, core/src/zeit/cms/interfaces.py, core/src/zeit/cms/patches.zcml, core/src/zeit/cms/repository/browser/README.txt, core/src/zeit/cms/repository/browser/tree.txt, core/src/zeit/cms/repository/folder.py, core/src/zeit/cms/security_patch.py, core/src/zeit/cms/tagging/browser/tag.py, core/src/zeit/cms/tagging/tag.py, core/src/zeit/cms/tagging/testing.py, core/src/zeit/cms/tagging/tests/test_tag.py, core/src/zeit/cms/testing.py, core/src/zeit/edit/block.py
About half of these are of general interest, so I hope it makes sense to already deal with those, even though zeit.cms is not completely done yet.
=> ZON-5645, ZON-5650: First slew of zeit.cms py3 updates

core/CHANGES.txt, core/src/zeit/wochenmarkt/categories.py
Looks like copy&paste error. Let jenkins double check.
=> MAINT: Remove unused imports

core/CHANGES.txt, core/src/zeit/content/article/edit/browser/resources/citation_comment.js
https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining
=> FIX: Remove optional chaining for better browser support

core/CHANGES.txt, core/src/zeit/wochenmarkt/browser/resources/recipe.js
Die Einheit "zweig" wird den Zutateneinheiten hinzugefuegt...
=> WOMA-136: Update list of ingredient units

core/CHANGES.txt, core/src/zeit/cms/browser/column.py, core/src/zeit/cms/content/dav.txt, core/src/zeit/cms/syndication/browser/feed.py, core/src/zeit/cms/syndication/feed.py, core/src/zeit/content/image/variant.py, core/src/zeit/edit/browser/view.py, core/src/zeit/edit/meta.py
JENKINS_BATOU_BRANCH=maint/interface
=> MAINT: Make forward-compatible to zope.interface-5.0

core/CHANGES.txt, core/src/zeit/wochenmarkt/browser/resources/recipe.js
=> WOMA-136_2: Update list of ingredient units

core/CHANGES.txt, core/src/zeit/content/author/honorar.py, core/src/zeit/content/author/interfaces.py, core/src/zeit/content/author/tests/test_honorar.py
=> ZON-5959: report deleted hdok authors

core/src/zeit/content/video/tests/test_browser.py, core/src/zeit/push/facebook.py, core/src/zeit/push/message.py, core/src/zeit/push/twitter.py
=> ZON-6041: Some minor code cosmetics after fd785e7

core/CHANGES.txt, core/src/zeit/cms/permissions.zcml, core/src/zeit/content/author/browser/configure.zcml, core/src/zeit/securitypolicy/security.zcml
Siehe [ZON-5981](https://zeit-online.atlassian.net/browse/ZON-5981).
=> ZON-5981: Restrict retract/delete for authors to producing

core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/edit/browser/form.zcml, core/src/zeit/content/article/edit/browser/tests/test_recipe_categories.py, core/src/zeit/content/article/interfaces.py, core/src/zeit/content/article/source.py, core/src/zeit/content/article/tests/article-genres.xml, core/src/zeit/content/article/tests/test_source.py, core/src/zeit/retresco/tests/test_convert.py
Was das alles soll: https://zeit-online.atlassian.net/browse/ZON-6098?focusedCommentId=66940
=> ZON-6098 option for publishing article to speechbert audio

core/CHANGES.txt, core/setup.py, core/src/zeit/content/text/jinja.py, core/src/zeit/content/text/tests/test_jinja.py, core/src/zeit/push/tests/test_urbanairship.py, core/src/zeit/push/urbanairship.py
=> ZON-6162: Update to jinja-2.11 API changes

core/CHANGES.txt, core/src/zeit/cms/content/interfaces.py, core/src/zeit/content/volume/interfaces.py
Belongs to c9157566 and #162… 🙄
=> OPS-1490: Allow volume to be set to 54 (everywhere)

core/CHANGES.txt, core/src/zeit/retresco/convert.py, core/src/zeit/retresco/tests/test_convert.py
Siehe [STO-172](https://zeit-online.atlassian.net/browse/STO-172).
=> STO-172: Be stricter about sending bool to TMS, since ES-7 is stricter

core/setup.py, core/src/zeit/push/tests/fixtures/payloadtemplate.json, core/src/zeit/push/tests/test_urbanairship.py, core/src/zeit/push/urbanairship.py
Nach dem ersten erfolgreichen Test dann mal einen PR...
=> ZON-6275: urbanairship open channel support

core/CHANGES.txt, core/src/zeit/content/modules/interfaces.py
=> ZON-6346: Make tickaroo liveblog status required

core/src/zeit/cms/admin/browser/admin.py, core/src/zeit/cms/content/interfaces.py
=> BEM-70: Remove py2 spellings

core/CHANGES.txt, core/src/zeit/retresco/convert.py, core/src/zeit/wochenmarkt/ingredients.py
We want to use a distinct Converter to make usage more clear
=> MAINT: Use distinct converter for RecipeArticles

core/src/zeit/cms/content/interfaces.py, core/src/zeit/content/article/testing.py, core/src/zeit/content/cp/testing.py, core/src/zeit/reach/__init__.py, core/src/zeit/reach/configure.zcml, core/src/zeit/reach/ftesting.zcml, core/src/zeit/reach/interfaces.py, core/src/zeit/reach/reach.py, core/src/zeit/reach/testing.py, core/src/zeit/reach/tests/test_reach.py, core/src/zeit/retresco/configure.zcml, core/src/zeit/retresco/testhelper.py, core/src/zeit/retresco/testing.py
Needs https://github.com/ZeitOnline/vivi-deployment/pull/178
=> TOPIC-31: Move code from z.w.core.reach to zeit.reach

core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/tests/test_recipe_categories.py, core/src/zeit/content/article/interfaces.py, core/src/zeit/retresco/tests/test_convert.py
Draft: erstmal schauen, welche tests umfallen
=> ZON-6482: articles with no genre have checked speechbert option

core/CHANGES.txt, core/src/zeit/content/article/edit/browser/resources/editor.js
Verhindert das Setzen von Verlinkungen mit internen Hosts im AAD.
=> ZON-6371: Avoid wrong host during set links

core/CHANGES.txt, core/src/zeit/retresco/content.py, core/src/zeit/retresco/interfaces.py, core/src/zeit/retresco/testing.py, core/src/zeit/retresco/tests/kpi.xml
Die Konfigurationsdateien habe ich in vivi staging+production bereits angelegt.
=> TOPIC-15: Make TMS kpi field names configurable

core/CHANGES.txt, core/src/zeit/content/dynamicfolder/folder.py, core/src/zeit/content/dynamicfolder/tests/test_folder.py
Bisher eher hemdsärmelig als gut, aber soweit sollte es funktionieren.
Nur das kommentieren funktioniert noch nicht.
=> ZON-6764: Add random (based on set title and uuid) uuid to dynamic pages

core/src/zeit/content/volume/browser/tests/test_toc.py, core/src/zeit/content/volume/browser/toc.py
Neuer PR, weil neuer Branch, weil mit dem Pushen im anderen Branch irgendwas nicht funzte
=> ZO-62: new csv style for toc export

core/CHANGES.txt
=> ZO-61: Update missing changelog entry

core/docs/changelog/ZO-188.maint, core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/content/volume/volume.py
Todo Toggle `cp30_wall_status_new_format` nach dem Deployment nach Staging und Production entfernen:
=> ZO-188: Remove feature toggle 

core/src/zeit/retresco/content.py
=> ZO-496: Add logging for AttributeError

core/docs/changelog/ZO-303.change, core/src/zeit/brightcove/update.py, core/src/zeit/content/video/video.py
at first: just for running tests on jenkins :)
=> ZO-303: Use built-in mechanics for publishing image with video

core/docs/changelog/ztk.maint, core/setup.py, core/src/zeit/content/image/browser/form.py, core/src/zeit/content/image/browser/imagegroup.py
JENKINS_BATOU_BRANCH=update-ztk
=> MAINT: Update to zope.publisher-6.0

core/docs/changelog/ZO-541.maint, core/src/zeit/vgwort/connection.py, core/src/zeit/vgwort/tests/test_connection.py
=> ZO-541: Remove old newsimport code

core/docs/changelog/ZO-1113.change, core/src/zeit/cms/checkout/webhook.py
@wosc : "falls es geholfen hat, kannst du dann nen ordentlichen PR stellen gelegentlich :)" -> hat geholfen, und so sind wir hier gelandet 🙃
=> ZO-1113: Log level info notify webhook

core/docs/changelog/ZO-365.fix, core/src/zeit/content/image/browser/form.py, core/src/zeit/content/image/browser/imagegroup.py, core/src/zeit/content/image/browser/tests/test_image.py, core/src/zeit/content/image/browser/tests/test_imagegroup.py
Re-issue of https://github.com/ZeitOnline/vivi/pull/296.
I hope I cherry-picken everything necessary. I something is missing please add it.
=> ZO-365: resize additional images in imagegroups while uploading

core/docs/changelog/ZO-633.change, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_contract.py
Currently disabled for ContractMock tests, as the search_result_default interferes.
=> ZO-633: Implement search for postgresql connector

core/docs/changelog/css_v2.fix, core/src/zeit/cms/browser/resources/forms.css, core/src/zeit/edit/browser/resources/editor.css
Should fix height of textarea when editing e.g. the feature-toggles.xml.
But I have no idea what I'm doing here and wether anything else breaks
=> FIX: height of xml textarea

core/src/zeit/cms/browser/resources/forms.css, core/src/zeit/content/text/browser/embed.py, core/src/zeit/content/text/embed.py, core/src/zeit/content/text/interfaces.py
removal of https://github.com/ZeitOnline/vivi/pull/26
=> ZO-1476: rm amp from pembeds

core/docs/changelog/tweepy.maint, core/setup.py, core/src/zeit/cms/browser/login.py, core/src/zeit/cms/testing.py, core/src/zeit/push/tests/test_twitter.py, core/src/zeit/push/twitter.py
JENKINS_BATOU_BRANCH=pipcompile
=> MAINT: Update to current tweepy and jwt API

core/docs/changelog/banner.maint, core/src/zeit/push/banner.py, core/src/zeit/push/tests/test_banner.py
JENKINS_BATOU_BRANCH=maint/transaction
=> MAINT: Publish breaking news banner directly together with its article

core/setup.py, core/src/zeit/cms/tests/test_tracing.py, core/src/zeit/cms/tracing.py
JENKINS_BATOU_BRANCH=maint/otel
=> MAINT: Update to current otel API, add smoketest

core/docs/changelog/ZO-1921.change, core/setup.py, core/src/zeit/connector/dav/davbase.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/testing.py
JENKINS_BATOU_BRANCH=maint/otel
=> ZO-1921: Instrument DAV requests for tracing

core/docs/changelog/ZO-1909.change, core/src/zeit/cms/testing.py, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py, core/src/zeit/workflow/tests/test_retract_3rdparty.py
=> ZO-1909: Use vivi api for speechbert publisher adapter

core/docs/changelog/ZO-1420.change, core/src/zeit/workflow/publish.py
Show all the systems, that have problems...
fand, es muss keinen Test für den Output des Errorlogs geben 🙊
=> ZO-1420: publisher error handling

core/docs/changelog/ZO-2042.change, core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/content/article/edit/browser/tests/test_videotagesschau.py, core/src/zeit/content/article/edit/videotagesschau.py, core/src/zeit/content/article/testing.py
Vorher bitte https://github.com/ZeitOnline/vivi-deployment/pull/398 (Einzeiler)
=> ZO-2042: use ard sync api (feature toggle depending)

bin/ci, core/src/zeit/connector/testing.py
Benötigt https://github.com/ZeitOnline/jenkins/commit/08f3dcf96f6d0b5fc2d7d73154116de962f3a9f6
=> ZO-2324: Move dav-server container image

core/docs/changelog/ZO-2856.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py
https://zeit-online.atlassian.net/browse/ZO-2856
=> ZO-2856: Remove slug from Speechbert image URL

core/docs/changelog/ZO-2757.changes, core/src/zeit/content/article/edit/browser/edit.py, core/src/zeit/content/article/edit/browser/tests/test_videotagesschau.py, core/src/zeit/content/article/edit/interfaces.py
Hinweis: Das hat mit dem _eigentlichen_ Ticket ZO-2757 nichts zu tun, aber beim Testen sind Rose und mir Fehler aufgefallen und wir haben gesagt, dass wir die schnell im Rahmen dieses Tickets abfangen.
=> ZO-2757: Handle input more flexible

core/docs/changelog/ZO-3028.fix, core/src/zeit/retresco/connection.py, core/src/zeit/retresco/tests/test_connection.py
sollte es das schon gewesen sein...?
=> ZO-3028: fix: import entity type for topicpages

core/docs/changelog/ZO-3245.change, core/setup.py, core/src/zeit/cms/repository/file.txt, core/src/zeit/connector/mock.py, core/src/zeit/content/image/browser/mdb.py, core/src/zeit/content/image/image.py
=> ZO-3245: Use pure python mime detection library

core/docs/changelog/ZO-1992.change, core/src/zeit/content/cp/testing.py, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/testing.py, core/src/zeit/workflow/tests/test_publish.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py, core/src/zeit/workflow/tests/test_retract_3rdparty.py
=> ZO-1992: Control TMS publish in vivi

core/docs/changelog/ZO-3351.fix, core/src/zeit/workflow/publish.py
Wir sind wieder zurück bei 5.26.5
=> ZO-3351: Revert lock and unlock for every function that requires the lock

bin/ci, core/docs/changelog/ZO-3443.change, core/setup.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/testing.py
=> ZO-3443: Update to sqlalchemy-2.x API

core/docs/changelog/ZO-2683.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py
=> ZO-2683: Add checksum to speechbert payload

core/docs/changelog/ZO-3172.change, core/setup.py, core/src/zeit/content/article/browser/breaking.py, core/src/zeit/push/configure.zcml, core/src/zeit/push/generation/__init__.py, core/src/zeit/push/generation/install.py, core/src/zeit/push/interfaces.py, core/src/zeit/push/testing.py, core/src/zeit/push/tests/fixtures/twitter-accounts.xml, core/src/zeit/push/tests/test_twitter.py, core/src/zeit/push/twitter.py
JENKINS_BATOU_BRANCH=ZO-3172
Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/558
=> ZO-3172: Update Twitter API to v2

core/docs/changelog/ZO-1949.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py, core/src/zeit/workflow/tests/test_retract_3rdparty.py
Ich frage mich hier im Draft etwas, ob ich die Aufgabe unter- oder überschätze...
Beachte auch https://github.com/ZeitOnline/publisher/pull/149
=> ZO-1949: remove uuid and uniqueId from 3rdparty payload

core/docs/changelog/ZO-3578.change, core/src/zeit/simplecast/configure.zcml, core/src/zeit/simplecast/json/configure.zcml, core/src/zeit/simplecast/json/webhook.py
JENKINS_BATOU_BRANCH=ZO-3578-simplecast-import
=> ZO-3578: Add Simplecast webhook(s)

core/docs/changelog/ZO-3671.fix, core/src/zeit/content/author/interfaces.py, core/src/zeit/content/author/tests/test_author.py
Whelp, maybe we hit the next limit in 10 years 🤷
=> ZO-3671: author ssoid is too big

core/docs/changelog/ZO-3661.change, core/src/zeit/content/audio/audio.py, core/src/zeit/content/audio/browser/form.py, core/src/zeit/content/audio/connection.py, core/src/zeit/content/audio/interfaces.py, core/src/zeit/content/audio/testing.py, core/src/zeit/content/audio/tests/__init__.py, core/src/zeit/content/audio/tests/test_audio.py, core/src/zeit/content/audio/tests/test_connection.py
Erster Aufschlag zur Anbindung der Simplecast API. Um die Änderungen übersichtlich zu halten, sollen die PRs kleinteilig sein. 
JENKINS_BATOU_BRANCH=ZO-3661_simplecast
=> ZO-3661: Simplecast API connection

core/docs/changelog/ZO-3744.change, core/src/zeit/simplecast/json/webhook.py, core/src/zeit/simplecast/testing.py, core/src/zeit/simplecast/tests/test_webhook.py
Habe mich in einem Rebase verwickelt und daher einen neue Branch erstellt. Hier ist an sich nicht viel passiert, weil das wichtigste Ziel ist, den Celery schnell zum laufen zu kriegen, um auf Staging die ganze Webhook Geschichte endlich mal vollständig funktionieren zu sehen.
Zusätzlich kommt vermutlich noch ein größerer Umbau, weil das Rad nicht neu erfunden werden soll.
JENKINS_BATOU_BRANCH=ZO-3744-celery
=> ZO-3744: Simplecast to celery

core/docs/changelog/celery.maint, core/src/zeit/content/audio/browser/form.py, core/src/zeit/content/audio/configure.zcml, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/json/webhook.py, core/src/zeit/simplecast/tests/test_connection.py, core/src/zeit/simplecast/tests/test_webhook.py
=> ZO-3701: Refactoring

core/docs/changelog/ZO-3771.change, core/src/zeit/content/audio/audio.py, core/src/zeit/content/audio/browser/form.py, core/src/zeit/content/audio/interfaces.py, core/src/zeit/content/audio/tests/test_audio.py
Add more properties, which successully hide in zeit.web templates
=> ZO-3771: Podcast serie subtitle and episode description 

core/docs/changelog/ZO-3851.changes, core/src/zeit/cms/tracing.py, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/tests/test_connection.py
- error handling
- request parameters
- timeout
- opentelemetry
=> ZO-3851: refactor: vivi common request handling

core/docs/changelog/ZO-3822.change, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/interfaces.py, core/src/zeit/simplecast/json/webhook.py, core/src/zeit/simplecast/tests/test_connection.py, core/src/zeit/simplecast/tests/test_webhook.py
=> ZO-3822: implement retract for audio objects

core/docs/changelog/ZO-4019.change, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/tests/test_connection.py
=> ZO-4019: Simplecast event 'Update Episode' can create a new episode if the episode does not exist

core/docs/changelog/ZO-4096.change, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/interfaces.py, core/src/zeit/simplecast/json/webhook.py, core/src/zeit/simplecast/testing.py, core/src/zeit/simplecast/tests/test_connection.py, core/src/zeit/simplecast/tests/test_webhook.py
=> ZO-4096: sync publish state even if episode is just added

core/docs/changelog/ZO-3967.maint, core/src/zeit/simplecast/tests/test_connection.py
A quick sanity check for the simplecast episode response. Does every look like we want it to look?
=> ZO-3967: add test for regular conformity check of simplecast response we get

core/docs/changelog/ZO-3904.change, core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/content/audio/reference.py
der Reload des Seitenkopfes im UI funktioniert noch nicht, aber der Test ist grün.
=> ZO-3904: article is podcast

core/pyproject.toml, core/src/zeit/cms/application.py, core/src/zeit/cms/celery.py, core/src/zeit/cms/tracing.py
This reverts commit f20308da423e365b825d0f563a3829b1b26f48ca, reversing changes made to 3dad8f965523d5f6bc27d25d0ef0e6c5ec27950e.
=> ZO-4130: Revert "Merge pull request #546 from ZeitOnline/ZO-3967"

core/docs/changelog/ZO-3764.change, core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/tests/test_article.py
=> ZO-3764: article title, teasertext and body automatically edited if audio is added

core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/tests/test_article.py
=> ZO-3764: article subtitle, teasertitle automatically edited if audio is added

core/docs/changelog/ZO-4254.change, core/src/zeit/cms/content/dav.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/content/audio/browser/tests/test_audio.py, core/src/zeit/content/audio/browser/tests/test_audioupdate.py, core/src/zeit/content/audio/testing.py, core/src/zeit/retresco/content.py, core/src/zeit/retresco/convert.py, core/src/zeit/retresco/ftesting.zcml, core/src/zeit/retresco/tests/test_content.py, core/src/zeit/retresco/tests/test_convert.py
=> ZO-4254: index audio objects

core/docs/changelog/ZO-862.change, core/src/zeit/cms/cli.py
and login functions
Siehe https://github.com/ZeitOnline/vivi-deployment/pull/760
=> ZO-862: add zope shell convenience function and add wait_for_commit

core/docs/changelog/ZO-4384.change, core/src/zeit/simplecast/connection.py, core/src/zeit/simplecast/interfaces.py, core/src/zeit/simplecast/json/webhook.py, core/src/zeit/simplecast/tests/test_webhook.py
=> ZO-4384: handle simplecast event transcode_finished

core/docs/changelog/ZO-4104.change, core/src/zeit/workflow/browser/resources/publish.js, core/src/zeit/workflow/json/publish.py, core/src/zeit/workflow/publishinfo.py
(do https://github.com/ZeitOnline/vivi/pull/573 again after broken rebase)
~- [ ] Documentation~
~- [ ] Tests~
~- [ ] Translations~
=> ZO-4104: retract validation fix

core/docs/changelog/ZO-4224.change, core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/speech/configure.zcml, core/src/zeit/speech/connection.py, core/src/zeit/speech/ftesting.zcml, core/src/zeit/speech/interfaces.py, core/src/zeit/speech/json/configure.zcml, core/src/zeit/speech/json/webhook.py, core/src/zeit/speech/testing.py, core/src/zeit/speech/tests/test_webhook.py
Das "Skelett" in Verbindung mit dem Deployment PR für unseren Webhook
Siehe auch [vivi-deployment/pull/788](https://github.com/ZeitOnline/vivi-deployment/pull/788)
=> ZO-4224: basic speech webhook added

core/docs/changelog/ZO-4321.fix, core/src/zeit/content/audio/browser/form.py
=> ZO-4321: Fields requires tuple

core/docs/changelog/pendulum.maint, core/pyproject.toml, core/src/zeit/cms/patches.zcml, core/src/zeit/cms/pendulum_patch.py
JENKINS_BATOU_BRANCH=dependabot/pip/components/source/pendulum-3.0.0
=> MAINT: Make pendulum-3.x work with zodbpickle

core/docs/changelog/ZO-4483.change, core/src/zeit/cms/content/serie.xml, core/src/zeit/cms/content/sources.py, core/src/zeit/cms/content/sources.txt, core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/content/audio/interfaces.py
=> ZO-4483: Set series if podcast episode is dropped into article

core/src/zeit/cms/workflow/mock.py
perhaps surprisingly, nothing broken 🤔
=> MAINT: Improve mock publish

core/docs/changelog/ZO-4460.change, core/src/zeit/cms/checkout/helper.py, core/src/zeit/cms/interfaces.py, core/src/zeit/content/article/article.py, core/src/zeit/content/article/interfaces.py, core/src/zeit/content/audio/audio.py, core/src/zeit/content/audio/interfaces.py, core/src/zeit/content/audio/reference.py, core/src/zeit/speech/connection.py, core/src/zeit/speech/errors.py, core/src/zeit/speech/ftesting.zcml, core/src/zeit/speech/json/webhook.py, core/src/zeit/speech/testing.py, core/src/zeit/speech/tests/test_connection.py, core/src/zeit/speech/tests/test_webhook.py
Reference the tts audio object in its corresponding article during creation via webhook by speechbert.
=> ZO-4460: Add tts to article

core/docs/changelog/ZO-4461.change, core/src/zeit/content/audio/audio.py, core/src/zeit/speech/connection.py, core/src/zeit/speech/interfaces.py, core/src/zeit/speech/json/webhook.py, core/src/zeit/speech/testing.py, core/src/zeit/speech/tests/test_connection.py, core/src/zeit/speech/tests/test_webhook.py
=> ZO-4461: Handle speechbert event AUDIO_DELETED

core/docs/changelog/ZO-4460.change, core/src/zeit/content/audio/interfaces.py, core/src/zeit/speech/connection.py, core/src/zeit/speech/tests/test_connection.py
=> ZO-4460: No enrich for audios, and check reference during tts update

core/docs/changelog/ZO-4225.change, core/src/zeit/content/article/article.py
PS to https://github.com/ZeitOnline/vivi/pull/599
=> ZO-4225: print article checksum object as its checksum

core/docs/changelog/audiotype.maint, core/src/zeit/content/audio/browser/details.py, core/src/zeit/content/audio/browser/tests/test_audio.py
Detail was mit an der Audiofläche aufgefallen ist
=> MAINT: use audio type translation in object detail view

core/docs/changelog/ZO-4226.change
=> ZO-4226: changes in vivi-deployment

core/docs/changelog/docker_logs.maint, core/src/zeit/connector/testing.py
=> MAINT: Log dav container logs for runtime error

core/docs/changelog/ZO-4549.change
just a changelog for vivi-deployment PR https://github.com/ZeitOnline/vivi-deployment/pull/847/
=> ZO-4549.change

core/docs/changelog/ZO-4881.change, core/src/zeit/connector/postgresql.py
=> ZO-4881: update table locks, foreign key to content table instead of paths

core/docs/changelog/ZO-4882.change, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_postgresql.py
properly remove blobs from collection
=> ZO-4882: remove locks after deletion of collection from children

core/docs/changelog/ZO-4913.change, core/src/zeit/cms/tagging/tag.py, core/src/zeit/cms/tagging/testing.py, core/src/zeit/cms/tagging/tests/test_tag.py
=> ZO-4627, ZO-4913: Add tags to XML only once

core/docs/changelog/ZO-4915.change, core/docs/changelog/ZO-4916.change, core/src/zeit/connector/postgresql.py
=> ZO-4915: copy optimization, clone row and copy blob directly on cloud storage

core/src/zeit/workflow/publish_3rdparty.py
=> MAINT: instead of list comprehension just use lower on that whole str

core/docs/changelog/ZO-5017.change, core/src/zeit/push/twitter.py
=> ZO-5017: IPushNotifier requires send

core/pyproject.toml
=> MAINT: lxml now requires lxml_html_clean package

core/docs/changelog/ZO-5085.change, core/src/zeit/cms/content/sources.py
=> ZO-5085: Support loading config files from storage api

core/docs/changelog/ZO-4974.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py, core/src/zeit/workflow/tests/test_retract_3rdparty.py
=> ZO-4974: remove feature toggle publish_bigquery_json

core/pyproject.toml
=> MAINT: Require lxml-html-clean library

core/docs/changelog/ZO-5142.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py
=> ZO-5142: Allow disabling publisher services with feature toggle "disable_publisher_NAME"

core/docs/changelog/ZO-4940.change, core/src/zeit/speech/connection.py
=> ZO-4940: invalidate cache of article if tts is created

core/docs/changelog/ZO-4966.change, core/src/zeit/content/cp/blocks/automatic.py, core/src/zeit/content/cp/browser/tests/test_automatic.py
=> ZO-4666: fix to save checkbox value for mobile images

ZO-5037.change
Just changes entry for https://github.com/ZeitOnline/vivi-deployment/pull/967
=> ZO-5037.change

core/docs/changelog/brightcove.maint, core/src/zeit/brightcove/tests/test_update.py, core/src/zeit/brightcove/update.py
=> MAINT: Allow disabling video export with feature toggle

core/docs/changelog/ZO-5378.change, core/src/zeit/speech/json/webhook.py, core/src/zeit/speech/tests/test_webhook.py
=> ZO-5378: if checksum is missing in AUDIO_CREATED event return 400 

core/docs/changelog/ZO-5394.change, core/src/zeit/cms/configure.zcml, core/src/zeit/cms/otel_patch.py, core/src/zeit/cms/patches.zcml
Die Upstream-Issue-Nummer bitte noch in `patches.zcml` einfügen :)
=> ZO-5394: Calculate requests client duration metric as ms

core/docs/changelog/ZO-5455.change, core/src/zeit/cms/history.py
=> ZO-5455: set config history upstream branch

core/docs/changelog/ZO-5461.change, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_postgresql.py
=> ZO-5461: fix steal lock

core/docs/changelog/ZO-5482.change, core/src/zeit/cms/workflow/mock.py, core/src/zeit/content/volume/browser/admin.py, core/src/zeit/content/volume/browser/tests/test_admin.py, core/src/zeit/workflow/publish.py, core/src/zeit/workflow/tests/test_publish.py
=> ZO-5482: move multi publish into per article celery task

core/src/zeit/connector/tests/test_postgresql.py
=> ZO-5471: Correct test

core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_postgresql.py
am besten commitweise anschauen
=> ZO-5471: Check feature toggle only on write, restrict checksum to body

core/docs/changelog/bodydata.maint, core/src/zeit/cms/browser/main_template.pt, core/src/zeit/cms/browser/standardmacros.py
This may help when developing bookmarklets or similar things
=> FEAT: Add uuid to UI HTML as body/data attribute

core/docs/changelog/ZO-5740.change, core/src/zeit/brightcove/tests/test_convert.py, core/src/zeit/content/article/edit/browser/tests/test_workflow.py, core/src/zeit/content/author/browser/honorar.py, core/src/zeit/content/image/browser/imagegroup.py, core/src/zeit/retresco/cli.py, core/src/zeit/sourcepoint/javascript.py, core/src/zeit/speech/testing.py, core/src/zeit/vgwort/browser/status.py, core/src/zeit/vgwort/cli.py
=> ZO-5470: Use pendulum instead of tz-less datetime.now()

core/docs/changelog/ZO-4617.maint, core/src/zeit/workflow/tests/test_publish.py
Mehr oder weniger zufällig drauf gestoßen, dass die wohl vergessen wurde, irgendwann zu entfernen.
=> MAINT: remove needless class

core/src/zeit/connector/migrations/postdeploy/20240709_1632-803bd7732cf6_add_index_to_name_and_parent_path_in_.py, core/src/zeit/connector/tests/test_migrations.py
=> ZO-4281: Lint migration code with squawk

core/docs/changelog/ZO-5407_ZO-5408.change
https://github.com/ZeitOnline/vivi-deployment/pull/1027
=> ZO-5407_ZO-5408: just changelog commit for vivi-deployment PR

core/docs/changelog/ZO-5697.change, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/testing.py, core/src/zeit/connector/tests/test_contract.py
replaces https://github.com/ZeitOnline/vivi/pull/804
=> ZO-5697: Read from paths columns

core/docs/changelog/ZO-5817-5885.change
https://github.com/ZeitOnline/vivi-deployment/pull/1100
=> ZO-5817-5885: just changelog entry for vivi-deployment

core/docs/changelog/MAINT-20240902tb.change
changelog for https://github.com/ZeitOnline/vivi-deployment/pull/1124
=> MAINT: update script template

core/src/zeit/content/gallery/gallery.py
=> MAINT: Set length of broken galleries to 0

core/pyproject.toml, core/src/zeit/cms/application.py
=> WCM-185: remove linesman, if we need benchmarks use pyinstrument like zeit.web does

core/docs/changelog/WCM-291.change, core/src/zeit/connector/migrations/postdeploy/20240912_1058-6cc99f5afdc5_add_channels_columns_.py, core/src/zeit/connector/migrations/postdeploy/20240925_1630-a4c1b7f678d9_create_index_for_timestamps.py, core/src/zeit/connector/models.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/testing.py, core/src/zeit/connector/tests/test_contract.py, core/src/zeit/connector/tests/test_migrations.py, core/src/zeit/connector/tests/test_postgresql.py
Also contains
* WCM-285: Make use of the "smaller" path_ops json index for `channels`
=> WCM-291: Add indexes so we can sort by timestamp columns

core/docs/changelog/WCM-435.change, core/src/zeit/connector/converter.py, core/src/zeit/connector/filesystem.py, core/src/zeit/connector/mock.py, core/src/zeit/connector/models.py, core/src/zeit/connector/tests/test_postgresql.py
=>  WCM-435: simultaneous write into dedicated columns and unsorted 

.gitignore, core/docs/changelog/WCM-285.change, core/src/zeit/connector/converter.py, core/src/zeit/connector/models.py, core/src/zeit/connector/tests/test_contract.py, core/src/zeit/connector/tests/test_mock.py, core/src/zeit/connector/tests/test_postgresql.py, core/src/zeit/connector/types.py
=> WCM-285: custom typ for jsonb to work with channels tuple type

core/docs/changelog/WCM-434.change, core/src/zeit/connector/converter.py, core/src/zeit/connector/mock.py, core/src/zeit/connector/tests/test_contract.py, core/src/zeit/connector/tests/test_mock.py, core/src/zeit/connector/tests/test_postgresql.py, core/src/zeit/retresco/content.py, core/src/zeit/retresco/tests/test_convert.py
=> WCM-434: convert native types in retresco

core/src/zeit/content/text/jinja.py
DEPLOYMENT_BRANCH=renovate/markupsafe-3.x
=> MAINT: markupsafe v3 upgrade json patch

core/docs/changelog/WCM-462.change, core/src/zeit/connector/models.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_postgresql.py
=> WCM-462: Toggle column access in batches, to support future migrations

core/docs/changelog/WCM-507.change, core/src/zeit/find/browser/find.py, core/src/zeit/find/browser/tests/test_selenium.py, core/src/zeit/find/search.py, core/src/zeit/find/tests/data/obama.json, core/src/zeit/find/tests/test_query.py
=> WCM-507: show author infos in search results

core/docs/changelog/WCM-519.change, core/src/zeit/cms/clipboard/browser/README.txt, core/src/zeit/cms/clipboard/browser/entry.py
=> WCM-519: redirect to index instead of view to open the working copy if available

core/docs/changelog/WCM-539.change, core/src/zeit/content/cp/tests/test_automatic.py, core/src/zeit/contentquery/query.py
=> WCM-539: Handle NULL in not-equal comparisons

core/docs/changelog/WCM-527.change, core/src/zeit/content/cp/tests/test_automatic.py, core/src/zeit/contentquery/interfaces.py, core/src/zeit/contentquery/query.py
=> WCM-527: sort by print_page not page

core/docs/changelog/wcm-466.change, core/src/zeit/content/article/article.py, core/src/zeit/content/article/tests/test_article.py
=> WCM-466: remove free/dynamic access toggle

core/docs/changelog/WCM-477.change, core/src/zeit/content/text/browser/configure.zcml, core/src/zeit/content/text/browser/jinja.py, core/src/zeit/content/text/interfaces.py, core/src/zeit/content/text/jinja.py, core/src/zeit/content/text/tests/test_jinja.py, core/src/zeit/push/tests/test_urbanairship.py, core/src/zeit/push/workflow.py
=> WCM-477: Update content channels from urbanairship template channels

core/src/zeit/cms/workflow/cli.py
=> WCM-558: never ever should publish by script trigger airship or speechbert

core/docs/changelog/WCM-566.change, core/src/zeit/cms/workflow/mock.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/speech/connection.py
=> WCM-566: only publish tts once in creation process

core/src/zeit/content/article/browser/tests/test_breaking.py, core/src/zeit/content/video/tests/test_browser.py, core/src/zeit/push/mock-webservice.zcml, core/src/zeit/push/real-webservice.zcml, core/src/zeit/push/testing.py, core/src/zeit/push/tests/test_urbanairship.py, core/src/zeit/push/urbanairship.py, core/src/zeit/push/workflow.py, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py
(publisher is responsible for this)
=> WCM-558: remove urbanairship push from vivi

core/src/zeit/entitlements/entitlements.py, core/src/zeit/entitlements/tests/test_entitlements.py
=> WCM-533: handle accepted entitlements can be overwritten

core/docs/changelog/WCM-574.change, core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/cms/content/sources.py, core/src/zeit/cms/ftesting-securitypolicy.zcml, core/src/zeit/cms/permissions.zcml, core/src/zeit/content/article/edit/browser/tests/test_videotagesschau.py, core/src/zeit/content/article/edit/videotagesschau.py, core/src/zeit/content/text/browser/configure.zcml, core/src/zeit/content/text/browser/embed.py, core/src/zeit/content/text/browser/tests/test_embed.py, core/src/zeit/content/text/embed.py, core/src/zeit/securitypolicy/security.zcml
=> WCM-574: remove more obsolete toggles

core/docs/changelog/bluesky_embeds.change, core/src/zeit/cms/content/feature-toggle.xml, core/src/zeit/content/article/edit/browser/edit.py, core/src/zeit/content/article/edit/browser/tests/test_embed.py, core/src/zeit/content/modules/tests/fixtures/embed-providers.xml
=> ZO-6758: Resolve account name in Bluesky post url

core/docs/changelog/otel.fix, core/src/zeit/revisions/revisions.py
=> FIX: Use wrong argument in telemetry span

core/docs/changelog/WCM-610.change, core/pyproject.toml, core/src/zeit/authentication/__init__.py, core/src/zeit/authentication/authentication.py, core/src/zeit/authentication/authentication.zcml, core/src/zeit/authentication/azure.py, core/src/zeit/authentication/configure.zcml, core/src/zeit/authentication/ftesting.zcml, core/src/zeit/authentication/oidc.py, core/src/zeit/authentication/testing.py, core/src/zeit/authentication/tests/__init__.py, core/src/zeit/authentication/tests/test_azure.py, core/src/zeit/authentication/zcml.py, core/src/zeit/cms/__init__.py, core/src/zeit/cms/generation/__init__.py, core/src/zeit/cms/generation/evolve18.py, core/src/zeit/cms/generation/evolve19.py, core/src/zeit/cms/generation/install.py
DEPLOYMENT_BRANCH=WCM-610-include-auth
Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/1234
=> WCM-610: Integrate zeit.ldap package as zeit.authentication

core/docs/changelog/WCM-617.change, core/src/zeit/authentication/authentication.py
=> WCM-617: provide fake root querysearchview

.github/workflows/testrunner.yaml, core/docs/changelog/wcm-610.maint, core/pyproject.toml, core/src/zeit/cms/browser/login.py
=> WCM-610: Remove zeit.ldap remnants

core/docs/changelog/WCM-626.change, core/src/zeit/content/dynamicfolder/folder.py, core/src/zeit/content/dynamicfolder/tests/test_folder.py
=> WCM-626: resolve load dynamic content with removed config

core/docs/changelog/ZO-2426_visual_submit_indicator.change, core/src/zeit/cms/browser/js/form.js, core/src/zeit/edit/browser/resources/editor.css
=> ZO-2426: Add visual submit indicator

core/docs/changelog/WCM-124.change, smoketest/k8s/base/kustomization.yaml, smoketest/k8s/base/secrets.yaml, smoketest/k8s/production/kustomization.yaml
=> WCM-124: Set up secrets in k8s

bin/test, core/docs/changelog/WCM-124.change, smoketest/Dockerfile, smoketest/Pipfile, smoketest/Pipfile.lock, smoketest/conftest.py, smoketest/test_vivi.py
=> WCM-124: Basic nightwatch vivi UI tests

core/docs/changelog/WCM-633.change, core/src/zeit/connector/cache.py, core/src/zeit/connector/tests/test_contract.py, core/src/zeit/objectlog/objectlog.py, core/src/zeit/objectlog/tests/test_objectlog.py
Nach Analyse der Exceptions die 2 Stellen abgefangen wo es auftritt.
=> WCM-633: handle property cache loss

core/docs/changelog/WCM-633.change, core/src/zeit/objectlog/objectlog.py
=> WCM-633: catch more generous the object log sweep exception

.gitignore, bin/test
=> MAINT: run vivi nightwatch locally

core/docs/changelog/WCM-698.change, core/src/zeit/connector/interfaces.py, core/src/zeit/connector/mock.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_contract.py
=> WCM-698: Implement exists, order, limit, offset for dav-style search

core/docs/changelog/WCM-699.change, core/src/zeit/content/link/browser/form.py
=> WCM-699: Remove social fields from link object form

core/docs/changelog/WCM-719.change, core/src/zeit/find/search.py
=> WCM-719: trace search query

core/docs/changelog/WCM-669.change, core/src/zeit/find/tests/test_search.py, core/src/zeit/retresco/connection.py, core/src/zeit/retresco/search.py, core/src/zeit/retresco/tests/test_connection.py, core/src/zeit/wochenmarkt/ingredients.py
=> WCM-669: add feature toggles to disable tms and elasticsearch completely

.gitignore, smoketest/conftest.py, smoketest/test_vivi.py
The nightwatch test has been adjusted in this test. It creates an article automatically via playwright, checks it in and out, aborts editing and deletes the article.
=> fix(nightwatch): fix test_checkout_content test [WCM-705]

core/docs/changelog/WCM-723.change, core/src/zeit/connector/models.py, core/src/zeit/connector/tests/test_postgresql.py
=> WCM-723: remove obsolete toggles

core/docs/changelog/cachetime.maint, core/src/zeit/cms/admin/browser/admin.py, core/src/zeit/cms/admin/browser/configure.zcml
=> WCM-743: allow caching time for all content types

core/docs/changelog/WCM-758.change, core/src/zeit/connector/migrations/postdeploy/20250304_0847-bc5b4e0b6bf9_add_vgwort_indexes.py, core/src/zeit/connector/migrations/predeploy/20250303_1202-2df03d84be31_add_vgwort_columns.py, core/src/zeit/connector/models.py
=> WCM-758: add vgwort columns

core/docs/changelog/WCM-26.change, core/src/zeit/connector/mock.py, core/src/zeit/connector/tests/test_mock.py, core/src/zeit/content/author/README.txt, core/src/zeit/content/author/author.py, core/src/zeit/content/author/browser/form.py, core/src/zeit/content/author/browser/honorar-duplicate.pt, core/src/zeit/content/author/browser/honorar.py, core/src/zeit/content/author/browser/tests/test_honorar.py, core/src/zeit/content/author/tests/test_author.py, core/src/zeit/content/author/tests/test_honorar.py, core/src/zeit/content/author/tests/test_reference.py, core/src/zeit/content/cp/tests/test_automatic.py, core/src/zeit/find/search.py, core/src/zeit/retresco/convert.py
=> WCM-26: Remove author properties in XML body, fully switch to DAV

core/src/zeit/cms/repository/interfaces.py, core/src/zeit/cms/repository/repository.py, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_postgresql.py, core/src/zeit/contentquery/query.py
=> WCM-657: Promote searching for ICMSContent by SQL to IRepository.search()

core/docs/changelog/WCM-473.change, core/src/zeit/connector/migrations/postdeploy/20250305_0915-68d8321b6387_create_index_for_author_lastname.py, core/src/zeit/connector/models.py, core/src/zeit/connector/tests/test_migrations.py
=> WCM-473: Add index to support searching for authors by umlaut-normalized lastname first-letter

core/docs/changelog/WCM-525.change, core/src/zeit/cms/content/dav.py, core/src/zeit/connector/tests/test_postgresql.py
=> WCM-525: support empty dates for nullable date columns

core/docs/changelog/WCM-767-height.change, core/docs/changelog/WCM-767.change, core/src/zeit/content/article/edit/browser/resources/editor.css, core/src/zeit/wochenmarkt/browser/resources/recipe.js, core/src/zeit/wochenmarkt/tests/test_ingredients.py
* Actually save entered ingredients parameters when adding another ingredient
* Remove height restriction on recipelist modules
=> WCM-767: Recipe/Ingredient module UI improvements and bugfixes

core/docs/changelog/WCM-786.change, core/src/zeit/workflow/publish_3rdparty.py, core/src/zeit/workflow/tests/test_publish_3rdparty.py, core/src/zeit/workflow/tests/test_retract_3rdparty.py
=> WCM-786: Explicitly specify the content types we publish in TMS

core/docs/changelog/WCM-694.change, core/src/zeit/connector/migrations/postdeploy/20250320_0922-b672aa0dd1e6_add_scheduled_publish_retract_indexes.py, core/src/zeit/connector/migrations/predeploy/20250317_1555-2a5901312f94_add_scheduled_publish_retract_columns.py, core/src/zeit/connector/models.py
=> WCM-694: add timebased publishing columns

core/docs/changelog/wcm-547.change, core/src/zeit/connector/migrations/postdeploy/20250325_1543-0ebf5005eb51_add_article_template_column.py, core/src/zeit/connector/migrations/predeploy/20250325_1536-8a302c7ec38c_add_article_template_column.py, core/src/zeit/connector/models.py
=> WCM-547: Add article_template column

core/docs/changelog/WCM-694.change, core/src/zeit/workflow/cli.py, core/src/zeit/workflow/tests/test_timebased.py
=> WCM-694: only publish if retract is in the future

core/docs/changelog/WCM-736.change, core/src/zeit/retresco/connection.py, core/src/zeit/retresco/testing.py, core/src/zeit/retresco/tests/test_connection.py
=> WCM-736: Remove secondary TMS, migration is now complete

core/docs/changelog/WCM-694.change, core/src/zeit/workflow/cli.py, core/src/zeit/workflow/tests/test_timebased.py
=> WCM-694: improve query for scheduled publish/retract

core/docs/changelog/WCM-694.change, core/src/zeit/connector/migrations/postdeploy/20250331_1336-f691fb06fe32_add_index_for_column_date_last_retracted.py, core/src/zeit/connector/models.py, core/src/zeit/workflow/cli.py, core/src/zeit/workflow/tests/test_timebased.py
=> WCM-694: skip scheduled publish if pre-conditions not satisfied

core/docs/changelog/WCM-807.change, core/src/zeit/connector/postgresql.py, core/src/zeit/connector/tests/test_contract.py
=> WCM-807: Implement OR operator in DAV-style connector search

core/docs/changelog/WCM-694.change, core/src/zeit/workflow/cli.py, core/src/zeit/workflow/tests/test_timebased.py
=> WCM-694: allow scheduled publish to republish content

core/docs/changelog/WCM-547.change, core/src/zeit/connector/models.py
=> WCM-547: Remove migration toggle for article_template column

core/docs/changelog/WCM-785.change, core/src/zeit/connector/migrations/postdeploy/20250409_1438-86f631fabdca_add_volume_date_digital_published_index.py, core/src/zeit/connector/migrations/predeploy/20250409_1438-7befcb5fd162_add_additional_volume_columns.py, core/src/zeit/connector/models.py, core/src/zeit/content/volume/testing.py, core/src/zeit/content/volume/tests/test_volume.py, core/src/zeit/content/volume/volume.py, core/src/zeit/vgwort/tests/test_report.py
=> WCM-785: storage query for previous/next for volume

core/docs/changelog/WCM-785.change, core/src/zeit/connector/models.py, core/src/zeit/content/volume/tests/test_volume.py, core/src/zeit/content/volume/volume.py
=> WCM-785: Remove feature toggle WCM-785 after migration

core/docs/changelog/WCM-830.change, core/src/zeit/cms/history.py
Siehe https://github.com/ZeitOnline/vivi-deployment/pull/1323
=> WCM-830: make confighistory work with non-root user account

core/docs/changelog/WCM-693.fix, core/src/zeit/content/volume/volume.py
=> WCM-693: Publish volume article after access change

core/docs/changelog/WCM-830.fix, core/src/zeit/cms/history.py
=> FIX: Broken git ssh call

core/docs/changelog/WCM-406.change, core/src/zeit/cms/workflow/cli.py
Wenn alles, was man hat, ein Hammer ist, sieht alles wie ein Monkeypatch aus...
=> WCM-406: Add --force-conditions flag to publish-content script to override can_publish

core/docs/changelog/WCM-838.change, core/docs/changelog/WCM-839.change, core/src/zeit/cms/content/dav.py, core/src/zeit/cms/interfaces.py, core/src/zeit/connector/converter.py, core/src/zeit/connector/models.py, core/src/zeit/connector/tests/test_postgresql.py, core/src/zeit/connector/types.py, core/src/zeit/content/article/article.py, core/src/zeit/content/article/edit/browser/form.py, core/src/zeit/content/article/interfaces.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/content/modules/configure.zcml, core/src/zeit/content/modules/interfaces.py, core/src/zeit/wochenmarkt/configure.zcml, core/src/zeit/wochenmarkt/interfaces.py, core/src/zeit/wochenmarkt/testing.py
=> WCM-838/WCM-839: write ingredients

core/docs/changelog/WCM-840.change, core/src/zeit/content/article/article.py, core/src/zeit/content/article/tests/test_article.py, core/src/zeit/wochenmarkt/interfaces.py, core/src/zeit/wochenmarkt/sources.py, core/src/zeit/wochenmarkt/tests/fixtures/categories.xml, core/src/zeit/wochenmarkt/tests/test_recipe_categories.py
=> WCM-840: Special categories

core/docs/changelog/wcm-888.change, core/src/zeit/vgwort/cli.py
Kann eigentlich nur das transaction commit sein
=>  WCM-888: commit transaction for vgwort report 

core/src/zeit/content/article/edit/browser/tests/test_embed.py
=> MAINT: Mark integration test

core/docs/changelog/wcm-901.change, core/src/zeit/content/image/tests/test_transform.py, core/src/zeit/content/image/transform.py
=> WCM-901: keep image exif metadata when resizing it

core/docs/changelog/WCM-959.change, core/src/zeit/wochenmarkt/recipe.py, core/src/zeit/wochenmarkt/tests/test_recipe.py
=> WCM-959: Don't duplicate special categories

core/pyproject.toml
DEPLOYMENT_BRANCH=dependamartin/pytest
=> MAINT: update pytest

core/docs/changelog/del.fix, core/src/zeit/content/image/image.py, core/src/zeit/content/image/tests/test_image.py
=> FIX: Safeguard around del

core/docs/changelog/WCM-954.fix, core/src/zeit/cms/content/keyreference.py, core/src/zeit/cms/repository/tests/test_copypastemove.py, core/src/zeit/content/link/redirect.py, core/src/zeit/objectlog/testing.py, core/src/zeit/objectlog/tests/test_objectlog.py
=> WCM-954: Derive child uniqueId correctly (trailing slash hell)

core/docs/changelog/WCM-982.change, core/src/zeit/cms/repository/repository.py, core/src/zeit/connector/interfaces.py, core/src/zeit/connector/mock.py, core/src/zeit/connector/postgresql.py, core/src/zeit/kpi/bigquery.py, core/src/zeit/kpi/ftesting-bigquery.zcml, core/src/zeit/kpi/ftesting.zcml, core/src/zeit/kpi/testing.py, core/src/zeit/kpi/tests/test_bigquery.py, core/src/zeit/kpi/tests/test_update.py, core/src/zeit/kpi/update.py, core/src/zeit/retresco/tests/test_connection.py
See commit messages for details.
=> WCM-982: Integrate KPI import cronjobs with connector cache

core/docs/changelog/WCM-983_log_zero.change, core/src/zeit/mediaservice/mediaservice.py, core/src/zeit/mediaservice/tests/test_mediaservice.py
=> WCM-983: Initialize counters to zero

core/docs/changelog/WCM-983_missing_volume_parts.change, core/src/zeit/mediaservice/connection.py, core/src/zeit/mediaservice/tests/test_connection.py
=> WCM-983: missing volume parts

core/docs/changelog/wcm-1045.change, core/src/zeit/mediaservice/mediaservice.py, core/src/zeit/mediaservice/tests/test_mediaservice.py
=> WCM-1045: support premium audio generation for articles with the same mediasyncid

core/docs/changelog/WCM-990_redirect_single_image.change, core/src/zeit/content/image/browser/imageupload.py, core/src/zeit/content/image/browser/tests/test_imageupload.py
=> WCM-990: Redirect single image

core/docs/changelog/WCM-1071_filename_from_xmp.change, core/src/zeit/cms/repository/browser/file.py, core/src/zeit/content/image/browser/imageupload.py, core/src/zeit/content/image/browser/tests/test_imageupload.py
=> WCM-1071: Overhaul image file name suggestion mechanism

core/src/zeit/content/article/edit/browser/tests/test_reference.py, core/src/zeit/content/image/README.txt, core/src/zeit/content/image/browser/README.txt, core/src/zeit/content/image/browser/imagefolder.txt, core/src/zeit/content/image/browser/master-image.txt, core/src/zeit/content/image/browser/tests/test_copyright.py, core/src/zeit/content/image/browser/tests/test_details.py, core/src/zeit/content/image/browser/tests/test_image.py, core/src/zeit/content/image/browser/tests/test_imagegroup.py, core/src/zeit/content/image/browser/tests/test_imageupload.py, core/src/zeit/content/image/browser/tests/test_purchase_report.py, core/src/zeit/content/image/browser/tests/test_variant.py, core/src/zeit/content/image/testing.py, core/src/zeit/content/image/tests/test_image.py, core/src/zeit/content/image/tests/test_imagereference.py, core/src/zeit/content/image/tests/test_metadata.py, core/src/zeit/content/image/tests/test_variant.py, core/src/zeit/content/image/transform.txt, core/src/zeit/workflow/tests/test_publish_3rdparty.py
=>  WCM-43: sql testsetup for image tests 

core/docs/changelog/WCM-1105.change, core/src/zeit/content/image/browser/form.py, core/src/zeit/content/image/browser/imageupload.py, core/src/zeit/content/image/browser/tests/test_imageupload.py
=> WCM-1105: Set timestamps in bulk image upload

core/docs/changelog/wcm-1123.fix, core/src/zeit/content/image/browser/resources/imageupload.js
eslint does not like missing break statements
=> WCM-1123: replace falltrough pattern

core/docs/changelog/wcm-1135.fix, core/src/zeit/content/image/image.py, core/src/zeit/content/image/tests/test_image.py
=> WCM-1135: support lists in metadata with mixed types

core/docs/changelog/wcm-1153.fix, core/src/zeit/content/image/image.py, core/src/zeit/content/image/tests/test_image.py
=>  WCM-1153: do not set mime type if image is copied 
