core/CHANGES.txt
core/src/zeit/content/gallery/workflow.txt
core/src/zeit/content/image/README.txt
core/src/zeit/content/image/image.py
core/src/zeit/content/image/testing.py
core/src/zeit/content/image/tests/test_image.py
core/src/zeit/content/image/tests/test_transform.py
core/src/zeit/content/image/transform.py

This saves a lot of unnecessary effort, e.g. when we only resolve an object to read its workflow properties or some such, and are not interested in its intrinsic properties at all. Also, while we only have read the first few bytes for the identification, zeit.connector always has to read the whole body, which then uses quite a bit of RAM.
Since be8134d we don't set the mime type explicitly anyway, and only use detection, so we don't lose any functionality here. We do lose the  safetybelt of "don't even resolve it if it's not an image/ mime type", but the only situation where that could be relevant is data corruption, and then an exception later on is fine as well, I think.

PERF: Determine image mime type only on demand, not always upfront on resolve

---

core/CHANGES.txt
core/src/zeit/cms/checkout/tests/test_webhook.py
core/src/zeit/cms/checkout/webhook.py
core/src/zeit/cms/testing.py

This ensures nothing is lost while we restart the contenthub processes (including the HTTP API) for a config update.

IR-66: Retry webhook on errors

---

core/CHANGES.txt
core/src/zeit/content/volume/browser/tests/test_toc.py
core/src/zeit/content/volume/browser/toc.py
core/src/zeit/content/volume/interfaces.py

Demnächst werden Print-Artikel sowohl unter `archiv-wf` als auch schon direkt in `work` landen, weil zeit.contenthub aus IR direkt nach vivi schreibt. Diese IR-Artikel sollen natürlich auch im Inhaltsverzeichnis landen.
Da es noch keine hinreichend "echten" IR-Testartikel gibt (beim Export fehlen immernoch Felder etc.), ist ungetestet, ob das hier die IR-Artikel wirklich korrekt mitnimmt. Ich habe allerdings schon ausprobiert, dass zumindest kein Unsinn (z.B. bereits ins vivi importierte K4-Artikel) mit reinkommt.

IR-142: Also collect articles imported from InterRed for volume table of contents

---

core/src/zeit/cms/browser/resources.py

needs: https://github.com/ZeitOnline/vivi-deployment/pull/81
JENKINS_BATOU_BRANCH=migrate-gocept-jasmine

Remove old function call for outdated fanstatic alpha

---

core/CHANGES.txt
core/src/zeit/cms/application.py
core/src/zeit/connector/cache.py

Deleting was definitely correct, but it caused thundering herd issues e.g. for often-used folders. We now switch to a simple "last request wins" for properties (which hopefully does not wrongly overwrite previous changed -- since concurrent accesses to the same object should be locked anyway). For childnames we go back to ConflictError/retry (since deleting would cause the folder properties to be deleted as well, to make the cache consistent), and hope that folder childnames to not conflict often.

OPS-1133: Modify DAV cache conflict resolution rules to avoid deleting cache entries

---

core/CHANGES.txt
core/src/zeit/cms/content/feature-toggle.xml
core/src/zeit/cms/content/sources.py
core/src/zeit/cms/ftesting-securitypolicy.zcml
core/src/zeit/cms/permissions.zcml
core/src/zeit/cms/type.py
core/src/zeit/cms/typegrokker.py
core/src/zeit/content/article/edit/browser/edit.py
core/src/zeit/content/cp/browser/blocks/rawtext.py
core/src/zeit/content/cp/browser/blocks/tests/test_rawtext.py
core/src/zeit/content/modules/rawtext.py
core/src/zeit/content/text/browser/configure.zcml
core/src/zeit/content/text/browser/tests/test_embed.py
core/src/zeit/content/text/embed.py
core/src/zeit/content/text/ftesting.zcml
core/src/zeit/securitypolicy/security.zcml

Changelog-Eintrag:
```
- ZON-5615: Require special permission to add embed objects,
set feature toggle `add_content_permission` to enable
- ZON-5615: Removed inline code entry from rawtext module  
```
Aus historischen Gründen gibt es zwei UI-Möglichkeiten, Content-Objekte anzulegen, direkt im Ordner oder über das "Hinzufügen"-Formular in der linken Spalte. Deshalb muss die neue Permission auch an zwei Stellen geprüft werden.

ZON-5615: Require special permission to add embed objects

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/resources/editor.js

This change should fix the RTE toolbar for Google Chrome browser.

ZON-5771: Make RTE toolbar compatible for Google Chrome

---

core/src/zeit/workflow/publish.py

Nach #53 und #56 war der Rest dann einfach… 🙂

ZON-5652: Product config always returns text, but we need an `int`

---

core/CHANGES.txt
core/src/zeit/edit/browser/tests/test_landing.py
core/src/zeit/edit/rule.py

das waren neulich noch deutlich mehr fails, die aber wahrscheinlich inzwischen im master mitgefixt wurden. zur sicherheit bitte trotzdem nochmal lokal tests laufen lassen a la `bin/test py3  vivi/core/src/zeit/edit`.

ZON-5651: Make zeit.edit py3 compatible

---

core/CHANGES.txt
core/src/zeit/brightcove/testing.py
core/src/zeit/brightcove/tests/test_update.py
core/src/zeit/brightcove/update.py
core/src/zeit/content/video/interfaces.py
core/src/zeit/content/video/playlist.py
core/src/zeit/content/video/testing.py
core/src/zeit/content/video/tests/test_browser.py
core/src/zeit/content/video/video.py

Dieser PR tut im wesentlichen drei dinge:
- erzeugt beim video import anhand der brightcove daten bildergruppen fuer die teaser bilder
- setzt neue attribute am video objekt, die jeweils eine dieser bildergruppen referenzieren
- macht den bestehenden brightcove importer goutierbar fuer das migrationskript

ZON-5635: add teaser image as cms content

---

core/CHANGES.txt
core/src/zeit/brightcove/convert.py
core/src/zeit/brightcove/tests/test_convert.py
core/src/zeit/brightcove/tests/test_update.py
core/src/zeit/brightcove/update.py
core/src/zeit/content/image/image.py
core/src/zeit/content/image/testing.py
core/src/zeit/content/image/tests/test_fetch.py
core/src/zeit/content/video/browser/video.py

nun werden auch updates von brightcove verarbeitet, allerdings so, dass falls seit dem ersten update manuell eine andere bildergruppe als vorschau oder thumbnail gewaehlt wurde, diese bilder dann vorrang haben

ZON-5635: add teaser image updates from BC

---

core/CHANGES.txt
core/src/zeit/cms/content/interfaces.py
core/src/zeit/cms/content/metadata.py
core/src/zeit/content/article/edit/browser/form.py
core/src/zeit/content/cp/browser/form.py
core/src/zeit/locales/de/LC_MESSAGES/zeit.cms.po
core/src/zeit/locales/zeit.cms.pot
core/src/zeit/retresco/tests/test_convert.py

Hiermit wird der Support für "die Weiche"™ auch aus Vivi entfernt.  Siehe [ZON-5861](https://zeit-online.atlassian.net/browse/ZON-5861).

ZON-5861: Remove marker for switching between old and new 'comments' API

---

core/CHANGES.txt
core/setup.py
core/src/zeit/campus/interfaces.py
core/src/zeit/cmp/interfaces.py
core/src/zeit/cms/browser/manual.py
core/src/zeit/cms/checkout/webhook.py
core/src/zeit/cms/content/sources.py
core/src/zeit/cms/retractlog/interfaces.py
core/src/zeit/content/article/edit/body.py
core/src/zeit/content/article/edit/header.py
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/content/article/source.py
core/src/zeit/content/author/interfaces.py
core/src/zeit/content/cp/interfaces.py
core/src/zeit/content/cp/layout.py
core/src/zeit/content/cp/source.py
core/src/zeit/content/gallery/source.py
core/src/zeit/content/image/interfaces.py
core/src/zeit/content/image/variant.py
core/src/zeit/content/link/sources.py
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/jobticker.py
core/src/zeit/content/volume/interfaces.py
core/src/zeit/imp/source.py
core/src/zeit/magazin/sources.py
core/src/zeit/push/interfaces.py

We no longer require an explicit path/url to be configured, but rather default to a central `config-base-url` setting if no explicit value is configured. This should vastly reduce the amount of boilerplate configuration needed (e.g. to differentiate between staging and production), since for most cases only the base-url has to be overridden now.

STO-49: Support setting a default filename for source config files

---

core/CHANGES.txt
core/src/zeit/wochenmarkt/browser/configure.zcml
core/src/zeit/wochenmarkt/configure.zcml

Das wurde bei den Aufraeumarbeiten uebersehen, ist jetzt in der Friedbert-Entwicklung aufgefallen, aber nicht dramatisch, da noch nicht verwendet wird.
Einmal Jenkins drueber laeufen lassen...

MAINT: Move browser imports from zeit.wochenmarkt to zeit.wochenmarkt.browser

---

core/CHANGES.txt
core/src/zeit/wochenmarkt/categories.py
core/src/zeit/wochenmarkt/ingredients.py

We need this at least for zeit.web, to make properties accessible, reading from ingredients- and categories-whitelists.

MAINT: Derive WOMA whitelists from z.c.c.sources.CachedXMLBase

---

core/src/zeit/wochenmarkt/categories.py

This has not been noticed until now because it seems to be made
available somewhere up in the dependency chain, but of course we
want to make the module work on its own.

MAINT: Add missing import

---

core/CHANGES.txt
core/src/zeit/content/modules/recipelist.py

Im Skript werden die Zutaten direkt via Adapter geladen und besitzen keine Werte für amount und unit. Das gibt beim Erstellen des XML's einen Fehler, welcher durch diese Anpassung aufgelöst wird.

WOMA-4: Add defaults for ingredient amount and unit

---

core/CHANGES.txt
core/src/zeit/cms/browser/resources/cms_widgets.css
core/src/zeit/content/article/edit/browser/tests/test_recipelist.py
core/src/zeit/content/modules/configure.zcml
core/src/zeit/content/modules/recipelist.py
core/src/zeit/content/modules/testing.py
core/src/zeit/content/modules/tests/test_recipelist.py
core/src/zeit/wochenmarkt/browser/resources/recipe.js
core/src/zeit/wochenmarkt/browser/widget.py

* Es gibt es neues Freitextfeld an Zutaten im Rezeptlistenmodul
* Die Liste der moeglichen Zutaten-Einheiten wurde erweitert
WOMA-115
WOMA-120
* Artikel auschecken
* Rezeptlistenmodul in Artikeltext ziehen
* Zutat via autocomplete hinzufuegen
1. Es existiert nun ein weiteres Eingabefeld. Der eingegebene Freitext wird im XML am Zutaten-Attribut `details` gespeichert 
2. Das dropdown einre Zutat umfasst nun die Werte aus WOMA-120

WOMA-115: Add free text details to ingredients in recipelist

---

core/CHANGES.txt
core/src/zeit/wochenmarkt/browser/resources/recipe.js

Zutaten werden als id gespeichert, damit diese spaeter (WOMA-112) via konfiguration uebersetzt werden koennen, z.b. um singular/plural-Darstellung zu ermoeglichen.

WOMA-130: Use ids for ingredient units

---

core/src/zeit/content/modules/tests/test_recipelist.py
core/src/zeit/content/volume/browser/tests/test_form.py
core/src/zeit/content/volume/tests/test_volume.py

JENKINS_BATOU_BRANCH=maint/deps-depr
Needs https://github.com/ZeitOnline/vivi-deployment/pull/128

MAINT: Update to lxml-4.4 which now keeps attribute order when initialized with a dict

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/tests/test_recipelist.py
core/src/zeit/content/modules/recipelist.py
core/src/zeit/content/modules/tests/test_recipelist.py
core/src/zeit/wochenmarkt/browser/resources/recipe.js

Bisher wurde verhindert, dass Zutaten doppelt hinzugefuegt werden koennen. Da es aber gelegentlich vorkommen kann, dass ein Rezept dieselbe Zutat mehrmals auflistet, ggf. unter veraenderten Werten fuer `Einheit` und/oder `weitere Angaben`, soll dies nun ermoeglicht werden.
Voraussetzung:
* Im Vivi einen Artikel anlegen
* Das Rezeptlistenmodul in den Artikeltext ziehen
Test:
1. Eine Zutat mehrfach hinzufuegen
* Ein bisschen mit den Werten rumspielen / neu sortieren etc.
* Die Zutaten muessen unabhaengig voneinander editiert werden koennen - wenn die z.B. die Mengenangabe fuer eine Einheit eingegeben wird, darf sie nicht auf die andere kopiert werden
* An jedem `li` muss eine eindeutige `data-id` haengen

WOMA-137: Allow duplicate ingredients in recipe list module

---

core/CHANGES.txt
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/tests/test_recipelist.py

Manche Portionsangaben wurden auf Grund von String-Vergleich falsch validiert. Jetzt wird explizit zu int konvertiert.
Voraussetzung:
* Artikel anlegen (Genre: Zeit Magazin)
* Rezeptlistenmodul in Artikeltext ziehen
Test:
* Portionsangabe a la `9-12` wird akzeptiert

WOMA-141: Update portion range validation for servings

---

core/src/zeit/content/modules/interfaces.py

Fügt der der `RecipeMetadataSource` eine Funktion hinzu, die die ganzen Knoten und nicht nur in Strings umgeformte Werte wie getValues zurückgibt. Wird im Skript WOMA-142 für das Korrigieren der alten Einheitennamen zu ihren entsprechenden Codes benötigt.

WOMA-142: Return nodes not just strings of RecipeMetadataSource

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/testing.py
core/src/zeit/content/article/edit/browser/tests/test_recipelist.py
core/src/zeit/content/article/ftesting.zcml
core/src/zeit/content/modules/browser/__init__.py
core/src/zeit/content/modules/browser/configure.zcml
core/src/zeit/content/modules/browser/sources.py
core/src/zeit/content/modules/browser/tests/__init__.py
core/src/zeit/content/modules/browser/tests/test_sources.py
core/src/zeit/content/modules/configure.zcml
core/src/zeit/content/modules/ftesting.zcml
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/testing.py
core/src/zeit/content/modules/tests/fixtures/recipe-metadata.xml
core/src/zeit/wochenmarkt/browser/resources/recipe.js

JENKINS_BATOU_BRANCH=WOMA-133
Muss gemeinsam mit folgendem PR gemergt werden: https://github.com/ZeitOnline/vivi-deployment/pull/131
Die Einheiten von Zutaten werden nun aus einer Konfigurationsdatei gelesen.
Voraussetzung:
* Einen Artikel anlegen
* Das Rezeptlistenmodul in den Artikeltext ziehen
* Eine Zutat hinzufuegen
Tests:
1. Einheit auswaehlen
1.1 In der Auswahl befinden sich die Einheiten aus der Konfiguration: https://vivi.staging.zeit.de/repository/data/recipe-metadata.xml
1.2 Der Name der Einheit entspricht dem XML-Attribut `singular`. Wurde Einheit ausgewaehlt, steht im XML des Artikels der Wert des XML-Attributs `code`.
2. Einheiten hinzufuegen/aendern
2.1 Den Wert `singular` oder `code` einer vorhandenen Einheit in der Konfiguration aendern oder eine weitere Einheit …

WOMA-133: Fetch ingredient units from configuration file

---

core/src/zeit/cms/browser/js/base.js
core/src/zeit/content/article/edit/browser/resources/html.js
core/src/zeit/content/article/edit/browser/tests/test_html.py

Siehe [BUG-1273](https://zeit-online.atlassian.net/browse/BUG-1273).

BUG-1273: Handle toplevel br nodes that can appear when pasting content

---

core/CHANGES.txt
core/src/zeit/content/gallery/browser/form.py
core/src/zeit/newsletter/category.py

BUG-1283: images in vivi image gallery editor are displayed using preview instead of view.html. this reduces their size as requested. Plus unforeseen PEP8 corrections.

BUG-1283: Size of images in image gallery editor is max 500 px times 500 px

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/resources/editor.js

We (still) need the ``<br>`` tag but it also works without the legacy
``type`` attribute. so instead of filtering it out during rendering, we
simply never add it in the first place now.

ZON-6108 invalid linebreaks

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/resources/editor.css
core/src/zeit/content/article/edit/browser/tests/test_recipelist.py
core/src/zeit/wochenmarkt/browser/resources/recipe.js

Wenn der Rezepttitel eines Rezeptlistenmoduls unausgefuellt ist, wird ein Hinweis ueber das Feld geschrieben. Dieser Hinweis ist nur optional zu beachten und hat keine Auswirkungen auf die Bearbeitung, das Einchecken oder Veroeffentlichen eines Artikels.
Der Hinweis erscheint in einem Marineblau um sich optisch zwar von einer Fehlermeldung abzuheben, Kontrast und Auszeichnung orientiern sich jedoch am gewohnten Vivi-Stil.
Testvorbereitung:
1. Rezeptartikel anlegen
2. Rezeptlistenmodul in Artikeltext ziehen
Testdurchfuehrung:
1. Der Hinweis sollte per default erscheinen
2. Wenn ein Rezepttitel vergeben wird verschwindet der Hinweis
3. Wenn der Rezepttitel wieder geleert wird, erscheint der Hinweis erneut

WOMA-181: Add notification for empty recipe title

---

core/CHANGES.txt
core/src/zeit/retresco/search.py

Fügt der Retresco Elasticsearch Klasse eine aggregate Methode hinzu, die aus dem ES JSON Objekt nur `aggregations` zurückgibt. Damit kann für Wochenmarkt einfach geprüft werden, welche Zutaten in Verwendung sind.
https://media.giphy.com/media/l46CslpFdTSgelr1u/giphy-downsized.gif

WOMA-204: Add aggregations to retresco.ElasticSearch query api

---

core/src/zeit/cms/content/browser/resources/dropdown.js
core/src/zeit/cms/content/browser/widget-subnav.txt
core/src/zeit/cms/content/browser/widget.py
core/src/zeit/cms/content/sources.py
core/src/zeit/content/article/article.py
core/src/zeit/content/article/edit/browser/form.zcml
core/src/zeit/content/article/edit/browser/template.py
core/src/zeit/content/article/edit/tests/templates.xml
core/src/zeit/content/article/interfaces.py
core/src/zeit/content/article/source.py
core/src/zeit/content/article/tests/article-templates.xml
core/src/zeit/content/article/tests/test_article.py
core/src/zeit/content/cp/interfaces.py

Abseits jeglicher rassistischen Sprachgewohnheiten implementiert dieser PR nun das gewuenschte dritte Dropdown mit Farbwerten fuer vollbreite Header visueller Artikel in Form einer verschachtelten Hierarchie von master/slave widgets.
TTW funktioniert es nun inswoweit, dass man die Werte in Abhaengigkeite der Header korrekt auswaehlen kann.
Was noch fehlt ist, dass das Farbendropdown auch wieder verschwindet, wenn man ein Template auswaehlt, das weder Header noch Farben unterstuetzt (bspw. "Kolumne").
Dieser PR ersetzt #131

ZON-6068 header color using master/slave widget

---

core/CHANGES.txt
core/src/zeit/content/image/imagegroup.py
core/src/zeit/content/image/tests/test_imagegroup.py

Mit diesem PR koennen alle bisher unterstuetzten Parameter der Imagegroup Varianten wahlweise auch in Form von Querystringparametern uebergeben werden.
Die Queryparameter haben dabei immer Vorrang gegenuber den Parametern, die Teil des Pfades sind.

ZON-6149: Allow to specify imagegroup variants via query parameters

---

core/CHANGES.txt
core/src/zeit/content/cp/blocks/teaser.py
core/src/zeit/content/cp/blocks/tests/test_automatic.py
core/src/zeit/content/cp/browser/blocks/tests/test_teaser.py
core/src/zeit/content/cp/interfaces.py

This PR should update the default `force_mobile_image` value for manually dragged teasers..
Ticket: [ZON-5577](https://zeit-online.atlassian.net/browse/ZON-5577)

ZON-5577: Update default for `force_mobile_image`

---

core/src/zeit/content/image/imagegroup.py
core/src/zeit/content/image/tests/test_imagegroup.py

Dieser PR macht, dass man image variants auch via query parameter (`?variant=cinema`) anfordern kann

ZON-6149: query parameters for image variants

---

core/src/zeit/push/browser/facebook.py
core/src/zeit/push/facebook.py
core/src/zeit/push/tests/test_facebook.py

Der Vivi-Test-Account hatte eine veraltete Version, sodass einige Berechtigungen nicht mehr aktuell waren.
Folgendes sollte auf staging getestet werden:
- neuen Facebook-Token für Vivi-Test anlegen
- testen ob das posten noch funktioniert

ZON-6196: Fix facebook post test for current api version

---

core/CHANGES.txt
core/src/zeit/content/modules/interfaces.py

Allows one more attribute from the config file to be read in zeit.web..

ZON-6140: Support additional attributes from newslettersignup config

---

core/CHANGES.txt
core/src/zeit/cms/settings/interfaces.py

Because in 2020 things are different.
Siehe [OPS-1490](https://zeit-online.atlassian.net/browse/OPS-1490).

OPS-1490: Allow volume to be set to 54

---

core/CHANGES.txt
core/src/zeit/push/browser/facebook.py

Es kann der Facebook-Test-Account verwendet werden.
Logins stehen in _{{vivi_deployment}}/components/test/buildout.cfg_ (ZEIT_PUSH_FACEBOOK_....)
Anleitung zum Testen siehe Ticket: [https://zeit-online.atlassian.net/browse/BUG-1315]()

BUG-1315: Fix Update-Token-Tool for Facebook

---

core/CHANGES.txt
core/setup.py
core/src/zeit/cms/tagging/browser/widget.py
core/src/zeit/retresco/connection.py
core/src/zeit/retresco/testing.py
core/src/zeit/retresco/tests/test_connection.py

> We can now set up a 'primary' and a 'secondary' TMS. For GET requests only the primary is used, for POST, PUT & DELETE the requests are sent to both. This should make testing and migration between different versions and/or deployments easier.
Siehe [STO-59](https://zeit-online.atlassian.net/browse/STO-59).
JENKINS_BATOU_BRANCH=STO-59-multi-tms

STO-59: Allow Vivi to talk to two TMS instances during migrations

---

core/src/zeit/cms/content/liveproperty.py
core/src/zeit/connector/cache.py
core/src/zeit/content/author/author.py
core/src/zeit/content/modules/rawtext.py
core/src/zeit/edit/container.py
core/src/zeit/newsletter/newsletter.py
core/src/zeit/retresco/content.py

Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working.

MAINT: Fix DeprecationWarning

---

core/setup.py

> This reverts cea6176a and brings back bf6cdf46, upgrading the `elasticsearch` client library to version 7.x again.
Siehe [STO-59](https://zeit-online.atlassian.net/browse/STO-59) / [STO-175](https://zeit-online.atlassian.net/browse/STO-175) & #171 & https://github.com/ZeitOnline/vivi-deployment/pull/160.
JENKINS_BATOU_BRANCH=STO-59-elasticsearch-7.x

STO-59: Upgrade the `elasticsearch` Python client library to 7.x

---

core/CHANGES.txt
core/setup.py
core/src/zeit/cms/browser/tests/test_widget.py
core/src/zeit/cms/browser/widget.py

Die Bibliotheken Markdown und Markdownify ersetzen Pandoc zur Konvertierung Makrdown <-> HTML. 
`vivi.cms.browser.widget.py`
`bin/test  vivi/core/src/zeit/cms/browser/tests/test_widget.py`
https://zeit-online.atlassian.net/browse/ZON-6383

ZON-6383: Handle Markdown using python libraries

---

core/CHANGES.txt
core/src/zeit/cms/content/sources.py
core/src/zeit/cms/content/tests/test_sources.py
core/src/zeit/content/article/edit/browser/configure.zcml
core/src/zeit/content/article/edit/browser/edit.py
core/src/zeit/content/article/edit/configure.zcml
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/content/article/edit/liveblog.py
core/src/zeit/content/article/edit/tests/modules.xml
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/liveblog.py
core/src/zeit/content/modules/tests/test_liveblog.py

Dieser PR stellt eine neues Artikelmodul "Tickaroo Liveblog" zur Verfuegung. Weil wir auf derzeit noch nicht absehbare Zeit die Bestueckung beider Liveblogsysteme unterstuetzen muessen, macht es aus Benutzer- und struktureller Sicht wenig Sinn beide Liveblog-Module zu mergen, sondern stattdessen parallel fuer jedes System eins anzubieten.
Ich war mir zunaechst nicht ganz sicher, wie schoen ich es finde, den Code mit dem Namen des Dienstleisters zu "branden", auf der anderen Seite erspart man sich so umstaendliche Verrenkungen bei der Benamsung und erkennt beim Lesen eindeutig um welches Liveblogsystem es sich handelt. Zumal sich mit wechselndem Dienstleister auch haeufig die Anforderungen aendern und wir dann beim naechsten mal wieder den gleichen Kopfstand machen muessten.
Bei Mailjet …

ZON-6346: Add article module for tickaroo liveblog

---

core/src/zeit/content/cp/blocks/markup.py
core/src/zeit/content/cp/interfaces.py

Fügt ein Attribute hinzu um den Zugriff auf in Markdown formatierten Text zu ermöglichen. Dies wird beispielsweise in Zappi benötigt, da nativ gerenderte Centerpages kein HTML enthalten dürfen.
gehört zu ZON-6383, dafür gibt es bereits einen `CHANGES.txt` Eintrag
https://zeit-online.atlassian.net/browse/ZON-6383

ZON-6383: Markdown property for markdown class

---

core/CHANGES.txt
core/src/zeit/content/author/browser/resources/author.css

https://zeit-online.atlassian.net/browse/BUG-1250
Der Hintergrund für die Ausblendung dieser Checkbox ist:
1) Der Anwender dachte er müsste sich zwischen 'ist external' und 'ist Autor' entscheiden.
Hier wurde dann 'ist Autor' deaktiviert und dies erzeugt den 404
Ob dies der Grund für die 404er oder nur ein Grund ist, wird sich noch zeigen müssen.
2) Dieses 'ist external' wird nicht mehr verwendet

BUG-1250: Hide no more needed 'external' author checkbox

---

core/CHANGES.txt
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/liveblog.py

Im Vivi muss in der `liveblog.xml` dafür das hier eingetragen werden.
```
<themes>
<theme id=default>Default</theme>
<theme id=solo>Solo</theme>
</themes>
```

ZON-6521: Support theme in liveblogs

---

core/src/zeit/cms/content/caching.py
core/src/zeit/cms/content/tests/test_filesystem_caching.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/mock.py

Attempt to refactor the connector/caching code to somewhat clean up the path & 'mtime' handling as discussed. Also see https://github.com/ZeitOnline/vivi/pull/183#discussion_r598655497
A number of tests are currently failing, so this is **WIP**.
> […] A good starting point to debug this is:
> ```
> $ bin/test vivi/core/src/zeit/cms/repository/
> ```
> Those are the only failures within `zeit/cms/`

STO-185: Clean up path/mtime handling

---

core/CHANGES.txt
core/src/zeit/content/modules/interfaces.py

Adds support for the new `legal_text` property which is needed in the newsletter.xml (`core/src/zeit/content/modules/tests/fixtures/newsletter.xml`).
I'm unsure wether or not we want to support any attribute in the xml and return it, therefore I didn't implement it right now.
If you think that makes sense, let me know and I'll find a way to add that, aswell :)

ZON-6573: Support legal_text attribute on newsletter signup widgets

---

core/CHANGES.txt
core/src/zeit/cms/admin/browser/admin.py
core/src/zeit/cms/admin/browser/tests/test_admin.py
core/src/zeit/cms/content/cachingtime.py
core/src/zeit/cms/content/configure.zcml
core/src/zeit/cms/content/interfaces.py
core/src/zeit/content/cp/browser/form.py
core/src/zeit/content/cp/centerpage.py
core/src/zeit/content/cp/interfaces.py

Um Cachingzeiten von Centerpages in Zukunft seitenspezifisch anpassen zu können, wird hier das Attribute `caching_time` analog zur `varnish_caching_time` in zeit.web eingeführt. Dieses Feature wird zunächst in Zappi verbaut, damit relative Zeitangaben von Teasern (vor 3 Minuten) nicht vom Cache ad absurdum geführt werden.

ZON-6614: Support caching_time attribute on centerpages

---

core/CHANGES.txt
core/src/zeit/content/image/imagegroup.py
core/src/zeit/content/image/tests/test_imagegroup.py
core/src/zeit/content/image/transform.py

Behebt den Fehler das Bildergruppen nicht gerendert werden, wenn die Hintergrundfarbe auf 'None' steht.
Wenn eine Url den Parameter _'...&fill=None'_ beinhaltet, ist dieser Wert ein _string_.
Es wurde beim setzen der Hintergrundfarbe aber nur auf _NoneType_ geprüft.
Dieser PR prüft ebenso, ob dieser Wert ein 'None'-string ist.
Siehe [ZON-6377](https://zeit-online.atlassian.net/browse/ZON-6377).

ZON-6377: Fixes that fill_color=None does not render image

---

core/CHANGES.txt
core/src/zeit/cms/content/feature-toggle.xml
core/src/zeit/content/article/edit/browser/edit.py

Mit diesem Toggle kann das Feld 'automatic_type' in den Topicboxen aus/eingeblendet werden.
Feature toggle heißt: 'show_automatic_type_in_topicbox'
Wenn der toggle 'false' oder nicht vorhanden ist, funktioniert die Topicbox wie früher und andere/neue Topicbox-Quellen können nicht ausgewählt werden.

MAINT: Add feature toggle to hide automatic_type in topicbox

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/configure.zcml
core/src/zeit/content/article/edit/browser/resources.py
core/src/zeit/content/article/edit/browser/resources/topicbox.css
core/src/zeit/content/article/edit/browser/resources/topicbox.js
core/src/zeit/content/article/edit/browser/tests/test_topicbox.py
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/contentquery/query.py
core/src/zeit/retresco/connection.py
core/src/zeit/retresco/interfaces.py

- Topicboxen einklappbar
- Related-API repariert
- Mehrere Topicboxen können in einem Artikel verwendet werden
- Naming: 'Konfigurationsdatei'-Label in 'Filter' geändert

ZON-6655: Rework topicbox

---

core/CHANGES.txt
core/src/zeit/content/cp/interfaces.py

Führt eine Regel ein, die leere Markdown module auf Centerpages verhindert.
`$ bin/test vivi/core/src/zeit/content/cp/tests/test_rule.py -sk test_markup_block_must_not_be_empty`
- Regel in staging und production nachziehen

OPS-1852: Markdown blocks must not be empty

---

core/CHANGES.txt
core/src/zeit/brightcove/connection.py

Wenn auf ein Video zugegriffen wird, das nicht abspielbar bzw. nicht aktiv ist, soll dazu kein Log geschrieben werden.
Videos die bei Brightcove hochgeladen werden, sind standardmäßig immer "nicht aktiv".
Diese werden erst später manuell auf aktiv gestellt.
Solange diese nicht "active" sind, wird bei Zugriff eine Menge an "VIDEO_NOT_PLAYABLE" - Logs geschrieben.

BEM-54: Improve Error-Logging for not playable videos

---

core/CHANGES.txt
core/src/zeit/content/article/edit/browser/resources/topicbox.js
core/src/zeit/content/article/edit/interfaces.py

Die Themenseiten-Sortieroption soll nur bei Auswahl von Themenseiten in Topicboxen im Artikel angezeigt werden.

FIX: Hide Topicpage sort option when anything else is selected

---

core/CHANGES.txt
core/src/zeit/content/image/tests/test_transform.py
core/src/zeit/content/image/transform.py

Wenn ein Bildzuschnitt den Parameter `size=(0,0)` bekommt, wirft PIL einen SystemError (tile cannot extend outside image).
Es wird versucht ein Bereich aus einem Bild herauszuschneiden, der über die Größe des Bildes geht.
Dieser PR setzt `size = None`, wenn min. ein Wert aus `size` 0 ist.

OPS-2024: Handles invalid variant size

---

core/CHANGES.txt
core/src/zeit/content/article/edit/tests/test_topicbox.py
core/src/zeit/content/article/testing.py
core/src/zeit/contentquery/query.py

Fügt der Funktion `_get_documents` in der `TMSRelatedApiQuery` den Parameter `order` hinzu.
Diese wird in der deren Superklasse verwendet und muss demnach auch hier definiert werden.
Der `order`-Parameter hat in der Related-Api aber keine Funktion und wird standardmäßig auf `None` gesetzt.
Außerdem `order` zu einer Property gemacht. Dadurch kann `TMSRelatedApiQuery` `order=None` setzen um den `cache`-Key nicht zu verwirren.

TOPIC-9: Make TMS order overridable, since related API does not support it

---

core/src/zeit/content/article/edit/browser/form.py

Ich habe (aus irgendwelchen Gründen) nach dem lokal Testen den Namen für das Formular geändert und es nicht nachgezogen, wo die Events registriert werden. Mit dieser Änderung hier ist es nun lokal getestet.

ZON-6316: FIX: change form name for autoreload with genre

---

core/CHANGES.txt
core/src/zeit/cms/content/interfaces.py
core/src/zeit/retresco/content.py
core/src/zeit/retresco/interfaces.py
core/src/zeit/retresco/tests/test_content.py

Es fiel auf, dass https://github.com/ZeitOnline/zeit.web/blob/8a520135c8e9c26c6f8ecc96c953b4ee2defd5fd/src/zeit/web/core/template.py#L1947 für TMSArticle nicht klappte. Deshalb musste ich die Stellen hier nochmal ein wenig anpassen. Außerdem hab ich den Test so angepasst, wie die Verwendung in zeitweb ist :)

MAINT: Add base KPI Implementation to ensure adapting it never fails

---

core/CHANGES.txt
core/src/zeit/content/cp/browser/resources/area.js
core/src/zeit/content/cp/browser/tests/test_automatic.py
core/src/zeit/reach/reach.py

Wenn reach als Datenquelle in Autoflächen ausgewählt wird soll die `Duplikate vermeiden` Checkbox ausgeblendet werden, sowie die `Autopilot` Checkbox per default angeklickt werden. Außerdem wird noch die Dauer zum timeout erhöht, weil sich gezeigt hat, dass 0.2s ein bisschen zu wenig sind!

TOPIC-39: UX Tweaks for reach as datasource

---

core/CHANGES.txt
core/src/zeit/content/cp/testing.py
core/src/zeit/content/cp/tests/test_automatic.py
core/src/zeit/contentquery/query.py

Während der Implementierung der Veränderungen in zeit.web sind weitere Fälle von Sortierungsmöglichkeiten aufgetreten. Daher werden hier diese Fälle mit berücksichtigt und vor allem Tests aktualisiert und nachgezogen, um diese Fälle in Zukunft schon in vivi abzusichern.
Diese Fälle enthalten:
- fehlende Sortierung `''`
- mehrere Sortierungen `'payload.xml.lastname:asc,payload.xml.firstname:asc'`

TOPIC-19: Be more defensive regarding sort order

---

core/CHANGES.txt
core/src/zeit/contentquery/query.py

We seem to receive nonexistent/ redirect URLs from the TMS which cannot
be converted and therefore throw an error. We just catch it now...
`devstaging` auf http://localhost:9090/thema/gerhart-hauptmann

FIX: Don't convert nonexistent pages

---

core/CHANGES.txt
core/src/zeit/retresco/connection.py
core/src/zeit/retresco/tests/test_connection.py

Sollte https://app.bugsnag.com/zeit-online-gmbh/friedbert/errors/60f136f65efb4a0007ebffea?filters[event.since][0]=30d&filters[error.status][0]=open fixen.

TOPIC-42: Fix IndexError when trying to request related topicpages

---

core/CHANGES.txt
core/src/zeit/brightcove/tests/test_update.py
core/src/zeit/brightcove/update.py

Nachfolger von #224 
Hier wird tatsaechlich nur ein fehlschlagen des updates von images (teaser und/oder still) im konkreten Fall eines vorhandenen Locks behandelt, in der annahme, dass das bild bearbeitet wird und deshalb sowieso nicht ueberschrieben werden sollte.

BUG-1430: gracefully handle locked images during brightcove import

---

core/docs/changelog/ZO-355.change
core/setup.py
core/src/zeit/cms/application.py
core/src/zeit/cms/browser/resources/lightbox.css
core/src/zeit/cms/celery.py
core/src/zeit/cms/cli.py
core/src/zeit/cms/security_patch.py
core/src/zeit/cms/testing.py
core/src/zeit/cms/ui.zcml
core/src/zeit/cms/zope.py

Basiert auf #260, den daher zuerst mergen.
JENKINS_BATOU_BRANCH=ZO-355
Ich würde glaub ich gern noch div. Module (wsgi, zope, logging etc) in ein Unterpaket zeit.cms.deploy o.ä. verschieben, damit besser klar wird, was wohingehört; hab das jetzt noch nicht getan, weil sonst die Diffs schwer lesbar wären. (Anschließend muss man zeit.ldap auf die geänderte API für dogpile.cache setup anpassen.)

ZO-355, ZO-358: Set up product config and zodb from settings/environ

---

core/docs/changelog/ZO-496.fix
core/src/zeit/reach/reach.py
core/src/zeit/reach/tests/test_reach.py
core/src/zeit/retresco/content.py

Fix für den Autoflächen Incident in vivi. Autoflächen stiegen mit `AttributeError: 'Article' object has no attribute '_tms_payload'` Außerdem aufräumen des Logging Eintrags.
`$ bin/serve$ und dann
`http://localhost:8080/repository/test/test-louisa/digital-index-production-kopie`
sowie
`$ bin/test vivi/core/src/zeit/reach/tests/test_reach.py`
https://zeit-online.atlassian.net/browse/ZO-496

ZO-496: Auto areas incident

---

core/docs/changelog/ZO-488.change
core/src/zeit/content/volume/browser/tests/test_toc.py
core/src/zeit/content/volume/browser/toc.py

Eindeutige ID (`ir_article_id`) für Artikel im Inhaltsverzeichnis der Ausgabe um die Zuordnung bei Änderungen zu erleichtern.
`$ bin/test vivi/core/src/zeit/content/volume/browser/tests/test_toc.py`
oder lokal 
`$ bin/serve`
und dann ein Ausgabenobjekt aufrufen, beispielsweise:
`http://localhost:8080/repository/2021/01/ausgabe/@@view.html`
und Inhaltsverzeichnis erzeugen. Am Ende der Zeile sollte bei Artikeln die  `article_id` im Format `1234567` stehen. Soweit ich sehen kann, sollen das sieben Ziffern sein.
https://zeit-online.atlassian.net/browse/ZO-488

ZO-488: Add article_id to volume toc

---

core/docs/changelog/ZO-582.change
core/src/zeit/content/volume/browser/configure.zcml
core/src/zeit/content/volume/browser/tests/test_toc.py
core/src/zeit/content/volume/browser/toc.py
core/src/zeit/content/volume/ftesting.zcml
core/src/zeit/content/volume/testing.py

Nach dem Release kann `vivi_zeit.content.volume_dav-archive-url` aus dem vivi-deployment entfernt werden.

ZO-582: Use vivi API for volume toc, this correctly includes author names

---

core/docs/changelog/ZO-680.change
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/liveblog.py

Hat etwas gedauert, bis ich gefunden habe, wo die einzelnen Felder angelegt werden... 🙄 (vlt für Louisa interessant: nämlich in `data/liveblog.xml`)

ZO-680: add intersection type choice field for liveblog module

---

core/src/zeit/connector/mock.py

Not sure, if that works as intended, or just resets with the results that a test set up.

ZO-538: Separate search results from search function

---

core/docs/changelog/ZO-365.fix
core/src/zeit/content/image/browser/form.py
core/src/zeit/content/image/browser/imagegroup.py
core/src/zeit/content/image/browser/tests/test_image.py
core/src/zeit/content/image/browser/tests/test_imagegroup.py

In the 'file list' view of an image group is another upload field. And so there is a view for uploading single images. Uploaded too large images from there were not resized to max image size. Now they are.

ZO-365: resize additional images in imagegroups while uploading

---

core/docs/changelog/ZO-1108.change
core/src/zeit/content/modules/interfaces.py

Aus der Kategorie ich wollt doch nur mal kurz gucken...
Habe festgestellt, dass wir für https://zeit-online.atlassian.net/browse/ZO-1108 auch den Vivi Code anpassen müssen und wollte ihn dann doch nicht komplett refactoren, deshalb schrieb ich's jetzt noch obendrauf.

ZO-1108: Support kicker in newsletter signup configuration, too

---

core/ZO-1212.change
core/src/zeit/content/cp/area.py
core/src/zeit/content/cp/browser/area.py
core/src/zeit/content/cp/browser/tests/test_area.py
core/src/zeit/content/cp/interfaces.py
core/src/zeit/content/cp/tests/test_area.py

Dieser PR erlaubt nun eine obtionale Hintergrundfarbe für Areas.

ZO-1212: Background color field for areas

---

core/docs/changelog/ZO-165.change
core/src/zeit/cms/repository/configure.zcml
core/src/zeit/cms/repository/folder.py
core/src/zeit/cms/repository/tests/test_folder.py
core/src/zeit/content/dynamicfolder/folder.py
core/src/zeit/content/dynamicfolder/tests/test_folder.py
core/src/zeit/workflow/publish.py

This gif says it all ...
Dieser PR repariert das Veröffentlichen von dynamischen Ordnern. Virtuelle Inhalte welche im DAV nicht existieren werden beim Veröffentlichen nicht mehr berücksichtigt.

ZO-165: Repair publish dynamic folder

---

core/docs/changelog/ZO-1255.change
core/src/zeit/content/cp/blocks/block.py
core/src/zeit/content/cp/browser/area.py
core/src/zeit/content/cp/browser/blocks/block.py
core/src/zeit/content/cp/browser/blocks/localteaser.py
core/src/zeit/content/cp/browser/region.py
core/src/zeit/content/cp/interfaces.py

Ich entferne nicht mehr notwendigen Code, weil wir dieses Feld als Tausch für das Hex-Farbwert an Areas Feld entfernen dürfen.
Erstmal als draft, bis der Friedbert Part durch ist, damit wir nicht irgendwo auf die Nase fallen...

ZO-1255: Remove possibility to hide regions/areas/modules on mobile devices

---

core/src/zeit/cms/browser/resources/cms.css

Error messages shall not move other inputs to the right.

FIX: Error messages shall not move other inputs

---

core/docs/changelog/ZO-114.change
core/src/zeit/content/animation/animation.py
core/src/zeit/content/animation/browser/configure.zcml
core/src/zeit/content/animation/browser/form.py
core/src/zeit/content/animation/interfaces.py

Der vierten Bulletpoint aus dem Ticket ("Podcast+Slideshow") wird hier erstmal ignoriert; ist nämlich noch nicht klar, was oder ob überhaupt dafür viviseitig etwas zu tun ist.

ZO-114: UI tweaks for Animation object

---

core/src/zeit/content/author/README.txt
core/src/zeit/content/modules/tests/test_recipelist.py
core/src/zeit/content/volume/browser/tests/test_form.py
core/src/zeit/content/volume/tests/test_volume.py

JENKINS_BATOU_BRANCH=ZO-859
Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/264

ZO-859: Update tests to lxml serialization changes

---

core/src/zeit/find/browser/find.py

Hmm, ich hab für die anderen Typen in den Tests nichts explizit gefunden (wenn "article" ausgewählt ist, dann werden nur Artikel gefunden). Oder habe ich nicht richtig geschaut?
Macht jedenfalls im Browser, was es soll.

ZO-1324: provide animation as filter for content types

---

core/docs/changelog/ZO-1375_vivi-find-search-fields.change
core/src/zeit/find/browser/find.py
core/src/zeit/find/search.py
core/src/zeit/find/tests/test_query.py

Hier müssen noch ein paar Sachen geklärt werden. Angeschaut wird sich das auch schon auf vivi.devel.

ZO-1375: read list of fields for fulltext search from config

---

core/docs/changelog/ZO-1603.change
core/src/zeit/retresco/convert.py
core/src/zeit/retresco/tests/test_convert.py

Die nötige [Typdeklaration](https://github.com/ZeitOnline/tms-deployment/commit/68e367d647182d65d8edb594f81fc4564707e561) habe ich bereits eingetragen (staging+production).

ZO-1603: Add "last indexed" field to TMS

---

core/docs/changelog/ZO-1576.change
core/src/zeit/cms/interfaces.py
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/content/cp/interfaces.py
core/src/zeit/content/link/browser/tests/test_link.py
core/src/zeit/content/link/interfaces.py

Die Übersetzung muss noch eingetragen werden; vielleicht vorher am sinnvollsten zuerst #365 mergen wg merge conflicts.
Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/294

ZO-1576: Implement hostname denylist for link targets

---

core/docs/changelog/masterimage.maint
core/src/zeit/content/image/imagegroup.py

The code from a2954b2 wanted to get the largest image, but always had a bug and just took the first one. Since this does not seem to have mattered at all, we make that behaviour explicit, which now yields a
significant performance benefit, as we do not have to get the image body (separately from GCS) to determine the size -- once we store that information in properties, we should revert this (and implement it
properly of course).

ZO-1858: Speed up bw-compat code for image group without master images

---

core/docs/changelog/ZO-1998.change
core/src/zeit/cms/content/sources.py

Um auf die Audio-App an Teasern verlinken zu können benötigen wir die ID an den Serien.. :)

ZO-1998: Support zonaudioapp-id in series.xml

---

core/docs/changelog/ZO-2132.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/edit/browser/edit.py
core/src/zeit/content/article/edit/browser/resources/html.js
core/src/zeit/content/article/tests/test_article.py

This basically changes the functionality from a very basic replacing pattern of quote characters to a slightly more complex one. Since this happens in Python and JS and since we need toggling, some more complexity was needed, which needs to be removed, when the feature is in production.

ZO-2132: Change normalisation of quotation marks

---

core/docs/changelog/ZO-1471.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/edit/browser/form.py
core/src/zeit/content/article/tests/test_article.py

vgl. https://github.com/ZeitOnline/vivi/pull/310/commits/b6ca07e54fe0a70369cff3c987c2857227b2696d

ZO-1471: undo copy teaser text to twitter field (ZO-920)

---

core/docs/changelog/ZO-2107.fix
core/src/zeit/connector/tests/test_cache.py
core/src/zeit/content/cp/browser/tests/test_area.py
core/src/zeit/content/image/browser/tests/test_variant.py

Not really a solution 😞 das ist quasi nicht lokal reproduziertbar, denn die Tests failen manchmal, wenn man alle Tests laufen lässt. Testet man selektiv sind die Tests grün.

ZO-2104: Mark unstable tests xfail

---

core/docs/changelog/ZO-1847.fix
core/src/zeit/content/cp/browser/blocks/layout.headerimage.content.pt
core/src/zeit/content/cp/browser/resources/editor.css

Auf Seiten mit Serienheader gab es folgenden Bug: die "Vorschau" des Serienheaders überdeckte das Vivi UI. Grund ist, dass der Text des Serienheaders absolut positioniert ist, um auf Headerbildern zu liegen. Wenn es allerdings kein Headerbild gibt, dann schiebt sich der Text über die Aufklappzeile vom Vivi UI.
Dieser Fix macht, dass die Zeile nur dann absolut positioniert wird, wenn es tatsächlich ein Headerbild gibt. Für diesen zweck haben wir auch das Template etwas umsortiert.
| vorher | nachher |
| ----- | ----- |
|![grafik](https://user-images.githubusercontent.com/148697/209151941-4306a62c-9bd1-4c34-84a7-7fb8d332cbcd.png)|![grafik](https://user-images.githubusercontent.com/148697/209151917-800e49b1-8203-4a25-8df2-de6060fdce33.png)|
Zu sehen zum Beispiel auf …

ZO-1847: Seriesheader preview should not cover Vivi UI

---

core/docs/changelog/ZO-2522.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/interfaces.py
core/src/zeit/content/article/tests/test_article.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/testing.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

Summary
---
We calculate the checksum of the body payload for speechbert, in order to verify that article body and speechbert audio match. Calculating the body for the speechbert payload twice, once before and once during the publish process, is not ideal. However, this implementation separates writing and reading operations, which is preferable to changing the properties of the article halfway during the publishing process.
How to test
---
well run the tests
```
$ bin/test vivi/core/src/zeit/content/article/tests/test_article.py -k checksum
```
or start local server with `$ bin/serve`. Create an article with a body containing text and publish it. Check the dav properties for the entry `checksum` this should contain an obscure hash, eg. `<attribute …

ZO-2522: Article checksum for speechbert

---

core/docs/changelog/ZO-2032.change
core/src/zeit/content/animation/animation.py

Animation acts as proxy for Article. If the Article reference is broken, animations must still provide the expected attributes.

ZO-2032: Always provide ICommonMetadata attributes

---

core/docs/changelog/ZO-3364.change
core/src/zeit/content/article/edit/animation.py
core/src/zeit/content/article/edit/browser/configure.zcml
core/src/zeit/content/article/edit/browser/edit.py
core/src/zeit/content/article/edit/configure.zcml
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/content/article/edit/tests/header-modules.xml
core/src/zeit/content/article/edit/tests/modules.xml
core/src/zeit/content/article/edit/tests/test_animation.py
core/src/zeit/content/article/tests/article-templates.xml

Dieser PR benennt das 'AnimatedHeader'-Modul in 'Animation' um.
Wenn das Modul ggf. auch in _nicht-Header_ verwendet werden soll, ist die Bezeichnung 'Animation' geeigneter.

ZO-3364: Renames 'AnimatedHeader' modul to 'Animation'

---

core/docs/changelog/ZO-3351.change
core/src/zeit/cms/checkout/browser/manager.py
core/src/zeit/cms/checkout/webhook.py
core/src/zeit/cms/content/liveproperty.py
core/src/zeit/cms/relation/corehandlers.py
core/src/zeit/content/article/edit/browser/save-and-publish.pt
core/src/zeit/content/gallery/workflow.txt
core/src/zeit/retresco/testhelper.py
core/src/zeit/retresco/tests/test_update.py
core/src/zeit/retresco/update.py

Test Dependency in [zeit.newsimport/pull/77](https://github.com/ZeitOnline/zeit.newsimport/pull/77)
JENKINS_BATOU_BRANCH=ZO-3351_update_newsimport

ZO-3351: race condition for asynchronous index tasks

---

core/docs/changelog/ZO-3351.change
core/src/zeit/cms/checkout/browser/manager.py
core/src/zeit/content/article/edit/browser/save-and-publish.pt
core/src/zeit/content/gallery/workflow.txt
core/src/zeit/retresco/testhelper.py
core/src/zeit/retresco/tests/test_update.py
core/src/zeit/retresco/update.py

we revert the changes, because the memory consumption on `vivi-task` and `vivi-app`. Local workflow tests are green 👍 
JENKINS_BATOU_BRANCH=ZO-3351_update_newsimport_again

ZO-3351: increased memory consumption

---

core/docs/changelog/ZO-2808.change
core/src/zeit/cms/content/browser/common_metadata_preview.pt
core/src/zeit/content/cp/browser/blocks/teaser.py
core/src/zeit/content/cp/browser/blocks/tests/test_teaser.py
core/src/zeit/content/markup/markup.py
core/src/zeit/content/markup/tests/test_markup.py

- ZO-2808: display teaser preview for markup in centerpage
- ZO-2808: display markup preview in folder list view
Lange Text werden gekürzt

ZO-2808: preview for markup in vivi

---

core/docs/changelog/ZO-2483.changes
core/src/zeit/workflow/publish.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

Erstmal schauen, ob der richtige Ansatz.
Einen Aufruf stelle ich mir so vor: https://github.com/ZeitOnline/vivi-deployment/commit/a9d438f36eb97e3a141265689056e10a37ff7f35

ZO-2483: option ignore 3rd party publishing

---

core/docs/changelog/ZO-3262.change
core/src/zeit/content/cp/blocks/rss.py

Usage and tests follow as a zeit.web PR ...

ZO-3262: Set target for RSS feed links (wiwo parquet)

---

core/docs/changelog/ZO-3550.change
core/src/zeit/cms/checkout/tests/test_webhook.py
core/src/zeit/cms/checkout/webhook.py

Stellt sich raus, neben News-Bildern häufen sich z.B. auch die Artikel, die von der Nachtwache alle paar Minuten veröffentlicht werden. Das ist vermeidbarer Datenmüll.

ZO-3550: Implement path prefix exclude for checkin webhook

---

core/docs/changelog/ZO-3718.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/tests/test_audio.py

Both `audios` and `audio` already exist as references to premium audio, therefore we require a new place to store podcast episodes.

ZO-3718: Audio container

---

core/docs/changelog/ZO-3708.change
core/docs/changelog/error_message.fix
core/src/zeit/campus/browser/social.py
core/src/zeit/content/article/edit/body.py
core/src/zeit/content/article/edit/browser/resources/editor.css
core/src/zeit/magazin/browser/social.py
core/src/zeit/push/browser/form.py
core/src/zeit/push/browser/resources/push.css
core/src/zeit/push/facebook.py
core/src/zeit/push/interfaces.py
core/src/zeit/push/tests/test_message.py
core/src/zeit/zett/browser/social.py

ZO-3708: vivi validation for social fields in article should prevent checkin

---

core/docs/changelog/ZO-3578.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/tests/test_audio.py
core/src/zeit/simplecast/connection.py
core/src/zeit/simplecast/interfaces.py
core/src/zeit/simplecast/json/webhook.py
core/src/zeit/simplecast/testing.py
core/src/zeit/simplecast/tests/test_connection.py
core/src/zeit/simplecast/tests/test_webhook.py

Use correct folder to save podcast episodes to storage, via simplecast webhook. 
[x] Tests
[x] Doku
[x] Test instructions
Ich habe angefangen [Doku](https://docs.zeit.de/vivi/implementation/simplecast.html) zu schreiben, aber da ist bestimmt noch viel Luft nach oben.
Testen
-------
Tests laufen lassen 
```
$ bin/test vivi/core/src/zeit/simplecast
$ bin/test vivi/core/src/zeit/content/audio
```
oder manuell den Webhook triggern, wie das geht, steht jetzt in der [Doku](https://github.com/ZeitOnline/vivi-deployment/pull/616). Anschließend prüfen, ob die Episode im richtigen Ordner gelandet ist.

ZO-3775: Correct podcasts folder

---

core/docs/changelog/ZO-3438.fix
core/src/zeit/connector/postgresql.py

It is a UUID but I think it's enough. Opentelemetry expects a str (or other simple types)

ZO-3438: ensure id for opentelemetry has type str

---

core/docs/changelog/ZO-3758.change
core/setup.py
core/src/zeit/push/facebook.py
core/src/zeit/push/interfaces.py
core/src/zeit/push/real-webservice.zcml
core/src/zeit/push/tests/test_facebook.py

Konfiguration in ZeitOnline/vivi-deployment@931eeb10, Doku in ZeitOnline/vivi-deployment@402eb206

ZO-3758: Remove `fb` facebook python library, talk directly to the HTTP API

---

core/docs/changelog/ZO-3770.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/browser/form.py
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/test_audio.py

Preparing migration in zeit.web, the audio interface should be used in templates and therefore we add the missing properties used inside the templates to replace the Podcast object dependency

ZO-3770: added new properties to audio interface

---

core/docs/changelog/ZO-3771.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/browser/form.py
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/test_audio.py

Audio object gets new empty dictionary for distribution channels of podcasts such as spotify, google, ios and so on. Its not visible in the ui and not yet set via the simplecast api call. We require the property for use in zeit.web
This is a preliminary fix in order to finish the implementation  in zeit.web.

ZO-3771: Subscriptions

---

.vscode/settings.json
core/docs/changelog/ZO-3821.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/browser/form.py
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/test_audio.py
core/src/zeit/content/cp/blocks/automatic.py

While we don't foresee audio objects using _most_ of the ICommonMetadata fields, they will use some (at least title, and later access, probably series), so in sum it's probably more helpful to use the interface than to not use it. (Just one example: This now automatically displays the title in directory listings)
Das gibt bestimmt nen Mergekonflikt mit #509 aber die Änderung hier ist so klein, das rebase ich im Anschluss dann gern.

ZO-3821: Audio objects provide ICommonMetadata, so they are indexed in TMS

---

core/docs/changelog/ZO-3933.change
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/fixtures/podcasts.xml
core/src/zeit/content/audio/tests/test_audio.py

Once added, we can start to write all data to `podcast.xml`

ZO-3933: Podigee_id attribute to podcast.xml

---

core/docs/changelog/layout_landing_zone_size.fix
core/docs/changelog/layout_publish_state.fix
core/docs/changelog/layout_remove_button.fix
core/src/zeit/cms/browser/resources/cms.css
core/src/zeit/cms/browser/resources/cms_widgets.css
core/src/zeit/cms/browser/resources/object_details.css
core/src/zeit/content/article/edit/browser/resources/editor.css
core/src/zeit/content/cp/browser/resources/editor.css

Small layout improvements that been fixed while creating #519 
---
**Before**
**After**
---
**Before** 
**After** 
---
**Before**
**After**

Minor layout fixes

---

core/docs/changelog/ZO-3824.change
core/src/zeit/simplecast/json/webhook.py
core/src/zeit/simplecast/tests/test_webhook.py

We also want to see informations about the webhook request _body_ in tracing

ZO-3824: more tracing for simplecast webhook requests

---

core/docs/changelog/ZO-3997.change
core/src/zeit/cms/permissions.zcml
core/src/zeit/content/audio/browser/configure.zcml
core/src/zeit/content/audio/browser/tests/test_audio.py

PR für Doku in Deployment und Anpassung der [components/zope/site.zcml](https://github.com/ZeitOnline/vivi-deployment/blob/main/components/zope/site.zcml) folgt.
Mit `<grant>` muss ich dem simplecast Principal dann ja die Rechte geben
- [vivi-deployment/pull/668](https://github.com/ZeitOnline/vivi-deployment/pull/668)

ZO-3997: restrict retract and delete permissions for audio

---

core/docs/changelog/ZO-3997.change
core/src/zeit/cms/permissions.zcml
core/src/zeit/content/audio/browser/configure.zcml
core/src/zeit/content/audio/browser/form.py

- Entfernt 1 click-Publish im Menü
- Entfernt unten die Action Buttons für Publish und Retract
Sofern TTS oder Premium einen anderen Workflow haben und es möglich ist diese selbst zu veröffentlichen, muss eine andere Lösung her.
`IPublishInfo` um `can_retract` erweitern o.Ä.

ZO-3997: Audio object form without publish or retract actions

---

core/docs/changelog/ZO-4198.fix
core/src/zeit/simplecast/connection.py
core/src/zeit/simplecast/tests/test_connection.py

Das ist am Ende erstmal ziemlich trivial. Nach meinem Verständis soll _immer_ veröffentlicht werden, wenn eine veröffentlichte Episode ans Vivi geschickt wird und _immer_ zurückgezogen werden, wenn eine unveröffentlichte Episode ans Vivi geschickt wird 🤷.
[Nachtrag](https://github.com/ZeitOnline/vivi/compare/8805f1c87f7f708849eadcbf75b259122220184c..616de3b3ccf2698203f9bd87a8a1e46e1616ac1a): Wenn das Audioobjekt unveröffentlicht ist und eine unveröffentlichte Episode ans Vivi geschickt wird, soll weder (selbsverständlich) weder veröffentlicht noch zurückgezogen werden (was nicht veröffentlicht ist)

ZO-4198: always call publish/retract if episode is(not) published

---

core/docs/changelog/ZO-4293.change
core/src/zeit/edit/browser/js/lightbox.js

ZO-4293: `load` event is being triggered for both tabs therefore check which tab we are in before setting form

---

.git-blame-ignore-revs
core/docs/changelog/ZO-4214.change
core/src/zeit/find/browser/find.py
core/src/zeit/find/browser/resources/search_form.jsont
core/src/zeit/find/browser/tests/test_selenium.py
core/src/zeit/find/search.py

Neues Feld erstellt für die Suche Audiotyp. Das Feld Podcasts ist deaktiviert wenn TTS oder Premium Audio auswählt ist.

 ZO-4214: add search filter for audio content type 

---

core/docs/changelog/ZO-4369.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/edit/audio.py
core/src/zeit/content/article/tests/test_article.py
core/src/zeit/content/audio/testing.py

We want all the paragraphs of the audio episode notes! Including but not limited to the very weird ones, without html tags.

ZO-4369: Format audio episode notes to correct html in article body

---

core/docs/changelog/ZO-4223.change
core/docs/changelog/layout.fix
core/src/zeit/cms/content/contentuuid.py
core/src/zeit/cms/content/tests/test_contentuuid.py
core/src/zeit/content/audio/browser/form.py

Wir übergeben Speechbert die Kurze UUID und bekommen diese entsprechend wieder zurück.

 ZO-4223: use short article uuid from speechbert to get content

---

core/docs/changelog/ZO-4496.change
core/src/zeit/simplecast/connection.py
core/src/zeit/simplecast/interfaces.py
core/src/zeit/simplecast/json/webhook.py
core/src/zeit/simplecast/testing.py
core/src/zeit/simplecast/tests/test_connection.py
core/src/zeit/simplecast/tests/test_webhook.py

ZO-4496: Retry celery task on simplecast 429 error

---

core/docs/changelog/ZO-4225.change
core/src/zeit/content/article/tests/test_article.py
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/reference.py
core/src/zeit/content/audio/testing.py

~Das macht in zeit.web bereits, was es soll. Ich versuche mich gerade noch darin, mehrer Audios unterschiedlichen Typs mit
```
AudioBuilder().with_audio_type('tts').build(self.repository)
self._add_audio_to_article()
```
an Artikel zu hängen.~ Ergänzung, damit das klappt, ist Teil des PRs

ZO-4225: filter audio references by audio type

---

core/docs/changelog/ZO-4612.change
core/src/zeit/cms/ftesting.zcml
core/src/zeit/cms/testing.py
core/src/zeit/connector/ftesting.zcml
core/src/zeit/content/article/ctesting.zcml
core/src/zeit/content/article/testing.py
core/src/zeit/content/audio/testing.py
core/src/zeit/content/gallery/testing.py
core/src/zeit/content/image/testing.py
core/src/zeit/content/volume/browser/tests/test_admin.py
core/src/zeit/edit/testing.py
core/src/zeit/retresco/ftesting.zcml
core/src/zeit/simplecast/testing.py
core/src/zeit/workflow/ctesting.zcml
core/src/zeit/workflow/ftesting.zcml
core/src/zeit/workflow/publish.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/publisher.py
core/src/zeit/workflow/publishinfo.py
core/src/zeit/workflow/testing.py
core/src/zeit/workflow/tests/test_publish.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

ZO-4612: Create publisher payload per content object and catch errors

---

.github/workflows/pre-commit.yaml
.github/workflows/testrunner.yaml

ZO-4513: Run tests (with batou) via GHA

---

core/docs/changelog/ZO-4649.fix
core/src/zeit/content/article/article.py
core/src/zeit/content/article/interfaces.py
core/src/zeit/speech/connection.py
core/src/zeit/speech/testing.py
core/src/zeit/speech/tests/test_connection.py

ZO-4649: calculate checksum of article body and compare against tts audio before adding audio reference

---

core/docs/changelog/ZO-4649.change
core/src/zeit/speech/json/webhook.py
core/src/zeit/speech/testing.py

The retry period for the celery task should cover one hour.

ZO-4649: Configure max retry for speech webhook

---

core/docs/changelog/ZO-3967.change
core/src/zeit/retresco/metrics.py

Wir wollen getrennte Alarme schreiben können dafür, wieviele Podcasts und wieviele TTS typischerweise laufend veröffentlicht werden, damit wir mitbekommen, falls eins davon stark sinkt. Dazu wird die Metrik `recent_audios` umgewandelt in `recent_content{content="podcast|tts|etc"}` (und nebenbei gleich noch der richtige Zeitstempel `last_published` statt `last_modified` verwewendet).
Wenn das nach Production deployed ist, muss man https://github.com/ZeitOnline/vm-prometheus-deployment/blob/main/deployments/kustomize/rules/vivi.rules.yaml anpassen:
```diff
-      expr: vivi_recent_news_published_total == 0
+      expr: vivi_recent_content_published_total{content="news"} == 0
-      expr: vivi_recent_videos_published_total == 0
+      expr: …
```

ZO-3967: Consolidate importer metrics with label `content=news, video, podcast, tts`

---

core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_doctest.py
core/src/zeit/connector/tests/test_doctest2.py
core/src/zeit/pytest.py

I noticed that no doctests are collected when running with our default of `bin/test -m 'not slow'`, which is way more harmful for developing than maybe having to explicitly select some tests in zeit.connector.

FIX: Don't try to add pytest mark to doctest, it seems to apply to *all* doctests

---

core/src/zeit/cms/workflow/interfaces.py
core/src/zeit/cms/workflow/status.py
core/src/zeit/cms/workflow/status.txt

We now control the modified timestamp ourselves (and intentionally do not update it at the publishing cycle checkin)

ZO-4687: Remove publish grace workaround

---

core/docs/changelog/ZO-4683.change
core/src/zeit/connector/testcontent/online/2022/08/trockenheit
core/src/zeit/speech/connection.py
core/src/zeit/speech/errors.py
core/src/zeit/speech/tests/test_connection.py

ZO-4683: Check date_last_modified instead of checksum

---

core/docs/changelog/ZO-4801-error.change
core/src/zeit/cms/browser/js/base.js
core/src/zeit/cms/browser/js/form.js
core/src/zeit/cms/browser/main_template.pt
core/src/zeit/cms/browser/standardmacros.py
core/src/zeit/cms/browser/tests/test_standardmacros.py
core/src/zeit/cms/content/feature-toggle.xml
core/src/zeit/cms/content/sources.py

We'll regret this if the server ever sends a full error page with styles and everything...

ZO-4801: Display request errors that occur in JS forms

---

core/docs/changelog/ZO-4267-unlock.change
core/src/zeit/connector/connector.py
core/src/zeit/connector/locking.txt
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/zopeconnector.py

See https://app.bugsnag.com/zeit-online-gmbh/vivi/errors/65ce29c518f4b10008a1f621
```
File "/srv/vivi/deployment/work/app/lib/python3.10/site-packages/zeit/workflow/publish.py", line 346,
in unlock
lockable.unlock()
File "/srv/vivi/deployment/work/app/lib/python3.10/site-packages/zope/app/locking/adapter.py", line 87
, in unlock
self.storage.delLock(self.context)
File "/srv/vivi/deployment/work/app/lib/python3.10/site-packages/zeit/cms/locking/locking.py", line 62
, in delLock
self.connector.unlock(object.uniqueId)
File "/srv/vivi/deployment/work/app/lib/python3.10/site-packages/zeit/connector/zopeconnector.py", lin
e 55, in unlock
locktoken = super().unlock(id, locktoken)
TypeError: Connector.unlock() takes 2 positional arguments but 3 were given
```

ZO-4267: Update ZopeConnector to changed unlock() API

---

core/docs/changelog/ZO-4267.change
core/src/zeit/connector/connector.py
core/src/zeit/connector/dav/davconnection.py
core/src/zeit/connector/dav/interfaces.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/interfaces.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_postgresql.py

ZO-4267: postgresql connector copy move lock

---

core/docs/changelog/ZO-4799.change
core/src/zeit/content/cp/blocks/automatic.py
core/src/zeit/content/cp/blocks/configure.zcml
core/src/zeit/content/cp/blocks/teaser.py
core/src/zeit/content/cp/blocks/tests/test_automatic.py
core/src/zeit/content/cp/browser/blocks/tests/test_teaser.py
core/src/zeit/content/cp/interfaces.py

ZO-4799: Remove obsolete rules about force_mobile_image defaults

---

core/pyproject.toml
core/src/zeit/content/text/json.py
core/src/zeit/content/text/tests/test_json.py

Aktualisierung der API-Nutzung von openapi-schema-validator um die aktuellen Versionen verwenden zu können.
Der folgende Deployment-Branch hat die entsprechend neuen Pins:
DEPLOYMENT_BRANCH=ZO-4053-2

ZO-4053: Update to current openapi-schema-validator API

---

core/docs/changelog/ZO-4886.change
core/src/zeit/cms/content/template.py
core/src/zeit/connector/lock.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/content/article/README.txt
core/src/zeit/content/cp/tests/test_leadtime.py
core/src/zeit/speech/tests/test_connection.py

dieser PR bezieht sich auf https://zeitverlagsgruppe.atlassian.net/wiki/spaces/Engineering/pages/3587440665/Sperren+von+Inhalten+im+Connector
Die Tests sind unter der Annahme geschrieben, dass sie nurnoch™️ Änderungen im Postgresql-Connector brauchen. Haben aber noch zu Anpassungen im MockConnector und in den Datenbanklassen geführt.

ZO-4886: check locking

---

core/docs/changelog/ZO-4726.change
core/src/zeit/connector/testcontent/zeit-magazin/wochenmarkt/rezept
core/src/zeit/content/article/article.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

Dieser PR fügt einen weitere Publish-Task hinzu, der eine Payload an den Publisher schickt, die von [diesem Summy PR](https://github.com/ZeitOnline/summy/pull/22) ausgewertet wird.
In der Payload sollten immer die Keys `uuid, uniqueId, summy` vorhanden sein.
Ein ignorierter Artikel hat ein leeres Objekt also summy-Key in der Payload: `"summy": {}`
[Dazugehöriger Deployment-PR](https://github.com/ZeitOnline/vivi-deployment/pull/897)
Ticket: [ZO-4726](https://zeit-online.atlassian.net/browse/ZO-4726)
[ZO-4726]: https://zeit-online.atlassian.net/browse/ZO-4726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ZO-4726: Adds summy publish task

---

core/docs/changelog/ZO-4800.change
core/src/zeit/cms/content/xmlsupport.py
core/src/zeit/cms/content/xmlsupport.txt
core/src/zeit/connector/cache.py
core/src/zeit/connector/cache.txt
core/src/zeit/connector/connector.py
core/src/zeit/connector/interfaces.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/tests/test_connector.py
core/src/zeit/connector/tests/test_postgresql.py

This avoids typos, that e.g. lead to trying to copy interal properties to XML (which then breaks because is_collection is a bool not a str).

ZO-4800: Use constants for internal properties

---

core/docs/changelog/ZO-5086.change
core/src/zeit/contentquery/interfaces.py

das Config Repo läd die Dateien nun in den `/data` Ordner, damit man sie von der dort manuell gepflegten Datei unterscheiden kann, heißt sie entsprechend `config-upload` 😬

ZO-5086: Update path and filename

---

core/docs/changelog/ZO-4940.change
core/src/zeit/workflow/publish.py
core/src/zeit/workflow/tests/test_publish.py

Damit wir es im staging testen können, aber abgesichert mit feature toggle

ZO-4940: feature toggle to disable transaction commit workaround for multi publish

---

core/docs/changelog/ZO-5022.change
core/src/zeit/cms/application.py
core/src/zeit/cms/celery.py
core/src/zeit/cms/relstorage.py
core/src/zeit/cms/tracing.py

ZO-5022: Enable tracing with sampling for sql connector

---

core/docs/changelog/foreign_lock.fix
core/src/zeit/connector/lock.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/tests/test_mock.py

Achtung während des [Umzugs](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/connector.py#L444) von `lock_is_foreign` haben wir das Vorzeichen umgedreht. Vorher hieß es `mylock = True` jetzt heißt es `lock_is_foreign = True` siehe [mock](https://github.com/ZeitOnline/vivi/blob/d6d69a64e352e6ed51a719ad504a1b7c137a4e80/core/src/zeit/connector/mock.py#L272)

ZO-4668: Do not break in zeit.web on missing ui dependencies

---

core/docs/changelog/ZO-4800.fix
core/src/zeit/content/image/image.py

ZO-4800: Remove obsolete class (belongs to a353c2c)

---

core/docs/changelog/ZO-5125.change
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_postgresql.py

Vermutlich am besten commitweise anschauen, enthält noch andere kleine Korrekturen.

ZO-5125: Cache lock data in property cache for sql connector

---

core/docs/changelog/ZO-4919.change
core/src/zeit/connector/configure.zcml
core/src/zeit/connector/gcsemulator.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_postgresql.py

- Für gcp-storage-emulator stell ich die Tage dann noch einen PR, falls der akzeptiert wird, können wir die Monkey-Patches hier dann wieder rauswerfen
- Ich hab keine naheliegende Idee, wie man das testen würde, dass das wirklich alles brav gebatched wird. Denn ich hab so ein Gefühl, dass wir uns eher _keinen_ Gefallen tun, wenn wir jetzt z.B. anfangen würden, SQL-Queries bzw GCS-Requests zu zählen (übers Tracing oder so). Denn das wird ja sehr schnell voller magischer Zahlen, wie viele Queries welche Operation ausführt.

ZO-4919: Use batch APIs for sql connector where possible

---

core/docs/changelog/ZO-5231.change
core/src/zeit/cms/interfaces.py
core/src/zeit/cms/repository/checkout.py

ZO-5231: use correct namespace for property renameable

---

core/src/zeit/content/dynamicfolder/tests/fixtures/dynamic-articles/template.xml

FIX: wrong namespace in example article

---

core/docs/changelog/ZO-5276.change
core/src/zeit/connector/postgresql.py

Bis wir Mechanik für Schema-Migrationen haben, hab ich mir das `CREATE INDEX` Statement [mit diesem sqlalchemy-Rezept](https://docs.sqlalchemy.org/en/20/faq/metadata_schema.html#how-can-i-get-the-create-table-drop-table-output-as-a-string) ausgeben lassen, und führe daher gleich `CREATE INDEX ix_properties_unsorted ON properties USING gin (unsorted jsonb_path_ops)` mal manuell aus.

ZO-5276: Use sql index to query unsorted properties

---

core/docs/changelog/ZO-5305.change
core/src/zeit/brightcove/update.py
core/src/zeit/retresco/connection.py
core/src/zeit/simplecast/connection.py
core/src/zeit/sourcepoint/javascript.py
core/src/zeit/speech/connection.py
core/src/zeit/speech/tests/test_connection.py
core/src/zeit/wochenmarkt/ingredients.py

Es existieren noch 3 `publish(background=False)`
`core/src/zeit/push/banner.py` hat ein `publish`, aber die Eilmeldung ist in keinem celery Task, sofern ich mich da nicht verguckt habe.
Sonst nur noch im `update_topiclist` cronjob, aber kann als unabhängige CLI selbständig commits machen.

ZO-5305: commit transactions before running publish inside celery tasks

---

core/docs/changelog/ZO-5282.change
core/src/zeit/workflow/timebased.py

eb4164e7f0615fa0f271a153548cabb7b1adfe5c introduced a breaking change to the arguments, therefore the function was never executed
... ich habs kaputt gemacht, hmpf

ZO-5282: retract overdue images

---

core/docs/changelog/ZO-5192.change
core/src/zeit/content/video/interfaces.py
core/src/zeit/content/video/video.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

[zeit.web](https://github.com/ZeitOnline/zeit.web/blob/main/src/zeit/web/core/template.py#L763-L765) baut sich Video URLs aus dem seo-slug und der uniqueId zusammen, genau so wie die [PushURL](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/video/video.py#L158-L161).

ZO-5192: Report complete video url to google pub/sub

---

core/docs/changelog/ZO-5358.change
core/src/zeit/cms/cli.py
core/src/zeit/cms/testing.py
core/src/zeit/cms/tests/test_cli.py
core/src/zeit/retresco/connection.py
core/src/zeit/wochenmarkt/ingredients.py
core/src/zeit/workflow/tests/test_publish.py
core/src/zeit/workflow/timebased.py

ZO-5358: Replace invalidate-based wait_for_commit helper with commit_with_retry

---

.github/workflows/nightwatch.yaml
bin/test
smoketest/conftest.py
smoketest/k8s/base/kustomization.yaml
smoketest/test_publisher.py

Achtung, das funktioniert erst, wenn #749 deployed ist.
Staging ist deployed, aber Production noch nicht, dh ich trag mal eine [Silence für Production ein](https://alertmanager.ops.zeit.de/#/silences/6a49780c-1151-457c-9790-f277c4d4c514), bis das nächste Woche dann deployed wird.

ZO-5272: Add smoketest for publishing an imagegroup

---

core/docs/changelog/ZO-4751.change
core/src/zeit/cms/workflow/cli.py
core/src/zeit/content/article/testing.py
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/testing.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

"Das bisschen" übriggebliebene Config wurde in https://github.com/ZeitOnline/vivi-deployment/commit/6fe718ef443bb708736c7d8188228591db79d33c entfernt.

ZO-4751: Remove unused facebook newstab integration

---

core/docs/changelog/ZO-5477.change
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/tests/test_postgresql.py

- instead of using self.session.refresh(Content) we explicitly set the object to avoid unnecessary database queries

ZO-5477: explicitly associates the lock with the content object

---

core/src/zeit/workflow/tests/test_publish.py

- the reason the tests fails sometimes in github action is still unknown though

FIX: instead of assert ellipsis, just look for the two imported value s inside the object log

---

core/docs/changelog/ZO-5193.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

ZO-5193: fix json representation of article body with whitespaces

---

core/docs/changelog/ZO-4281.change
core/pyproject.toml
core/src/zeit/connector/cli.py
core/src/zeit/connector/configure.zcml
core/src/zeit/connector/migrations/alembic.ini
core/src/zeit/connector/migrations/env.py
core/src/zeit/connector/migrations/predeploy/20220124_1552-553e4856ccbb_add_table_properties.py
core/src/zeit/connector/migrations/predeploy/20220216_1048-6392b9450475_add_table_paths.py
core/src/zeit/connector/migrations/script.py.mako
core/src/zeit/connector/tests/test_migrations.py

DEPLOYMENT_BRANCH=ZO-4281-alembic
Die hier "nachgetragenen" Migrationen habe ich manuell als aktiv markiert (devel/staging/production, internal/public):
`env 'alembic_dsn=postgresql://?service=vivi-internal-devel' work/app/bin/alembic-vivi --name predeploy stamp head`

ZO-4281: Set up alembic for database migrations

---

core/docs/changelog/ZO-5779.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

ZO-5779: Skip XML comments in BigQuery JSON serialization

---

core/docs/changelog/toggle.maint
core/src/zeit/connector/postgresql.py

Goodbye 👋 Tests sind local grün, keine weiteren Einträge des Toggles irgendwo gefunden

MAINT: remove feature toggle

---

core/src/zeit/connector/postgresql.py
core/src/zeit/connector/tests/test_postgresql.py

Unblocking PR bis ZO-5795 implementiert

ZO-5176: workaround to unblock deployments until ZO-5795 is implemented

---

core/docs/changelog/ZO-4165.change
core/pyproject.toml
core/src/zeit/content/text/browser/json.py
core/src/zeit/content/text/browser/tests/test_json.py
core/src/zeit/content/text/json.py
core/src/zeit/content/text/tests/test_json.py

die Fehlermeldung war vorher auch nicht übersetzt.
DEPLOYMENT_BRANCH=ZO-4165_rm_commentjson

ZO-4165: Replace commentjson with rapidjson and support comments

---

core/docs/changelog/ZO-5850.change
core/src/zeit/connector/cli.py
core/src/zeit/connector/tests/fixtures/alembic/alembic.ini
core/src/zeit/connector/tests/fixtures/alembic/conflict/000000000001.py
core/src/zeit/connector/tests/fixtures/alembic/conflict/000000000002.py
core/src/zeit/connector/tests/fixtures/alembic/conflict/000000000003.py
core/src/zeit/connector/tests/fixtures/alembic/three/000000000001.py
core/src/zeit/connector/tests/fixtures/alembic/three/000000000002.py
core/src/zeit/connector/tests/fixtures/alembic/three/000000000003.py
core/src/zeit/connector/tests/fixtures/alembic/two/000000000001.py
core/src/zeit/connector/tests/fixtures/alembic/two/000000000002.py
core/src/zeit/connector/tests/test_migrations.py

Since we don't always update the code in lock-step with the DB in different systems, we need to be more lenient here.

ZO-5850: Don't wait if the DB revision is newer than what we know on disk

---

core/docs/changelog/ZO-5548.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

Neuen Publisher-Workflow für [IndexNow](https://www.bing.com/indexnow) hinzugefügt.
[Ticket: ZO-5548](https://zeit-online.atlassian.net/browse/ZO-5548)
Vault-PR: https://github.com/ZeitOnline/vault/pull/250

ZO-5548: add index now configuration

---

core/docs/changelog/namespaces.maint
core/src/zeit/cms/interfaces.py
core/src/zeit/content/cp/interfaces.py

related https://github.com/ZeitOnline/vivi/commit/90cb829c9c1fabc3d82879fa75efb4d7f0be0ba5 and https://zeit-online.atlassian.net/browse/DEV-852

MAINT: Rm obsolete namespaces

---

core/docs/changelog/encoder.fix
core/src/zeit/content/image/interfaces.py
core/src/zeit/content/image/tests/fixtures/encoders.xml
core/src/zeit/content/image/tests/test_transform.py

FIX: Adjust image-encoders.xml config file format so it actually works

---

core/docs/changelog/ZO-5817-5884.change

(just for vivi-deployment https://github.com/ZeitOnline/vivi-deployment/pull/1096 changelog)

ZO-5817-5884: script rm-outdated-parquet-areas.py

---

core/docs/changelog/WCM-271.change
core/src/zeit/cms/content/dav.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/models.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_migrations.py
core/src/zeit/connector/tests/test_postgresql.py

Wenn das released ist, vivi-Version in https://github.com/ZeitOnline/content-storage-api/pull/284 hochziehen, dann ist der entblockiert.

WCM-271: Use entirely separate model classes for developing columns

---

core/docs/changelog/ZO-5819.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

Das ist ein Pull-Request für Ticket [ZO-5819](https://zeit-online.atlassian.net/browse/ZO-5891). Data-Science pflegt und nutzt einen `Google Cloud Storage Bucket`, um ihre Analysen zu machen. Bei jedem Publish werden die Dateien in diesen Bucket gelegt (einmal Metadaten, einmal Body).
In diesem Pull Request wird ein neuer Publish-Workflow angelegt. Dabei wird der `body` roh und `meta` als JSON mitgegeben.  
[ZO-5819]: https://zeit-online.atlassian.net/browse/ZO-5819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ZO-5819: add export to datascience implementer

---

core/docs/changelog/WCM-268.change
core/src/zeit/cms/checkout/tests/test_webhook.py
core/src/zeit/cms/checkout/webhook.py
core/src/zeit/cms/content/products.xml
core/src/zeit/cms/content/sources.py
core/src/zeit/cms/content/tests/test_sources.py
core/src/zeit/cms/workflow/cli.py
core/src/zeit/workflow/tests/test_publish.py

Um den Interred Webhook entweder während des Checkins oder während des Veröffentlichens Bescheid zu sagen, kann man nun mehrere `<webhook>` Tags in der `checkin-webhooks.xml` anlegen. Damit das funktioniert gibts nun für jeden eine `id` und nicht nur eine `url` um den Webhook zu identifizieren. 
Zusätzlich kann man nun den das Attribute `counter` aus der `products.xml` als `exclude` nutzen, sodass man z.B. `<product_counter>online</product_counter>` oder `print` in die `checkin-webhooks.xml` eintragen kann. 
Warum so? Warum nicht eine extra XML-Resource? Damit die Informationen, wann welche Inhalte an Interred geschickt werden, nicht über mehrere Source-Files verstreut sind.

WCM-268: Export to Interred during checkout or publish 

---

core/docs/changelog/WCM-268.change
core/src/zeit/cms/checkout/webhook.py

Unfortunately celery does not want to take the hook object and has to search for the hook again

WCM-268: Unfortunately celery does not want

---

core/docs/changelog/formsave.fix
core/src/zeit/cms/browser/js/form.js

WCM-311: Revert Remove delay from inline form save, to avoid overlapping with other actions (that were triggered immediately)

---

core/docs/changelog/connector.fix
core/src/zeit/connector/mock.py

Da wir häufiger den MockConnector mit einer anderen Resource ausstatten, ist ein Setting mal angebracht um genau dies zu machen.
https://github.com/ZeitOnline/content-storage-api/pull/295#discussion_r1735917505

FIX: make resource_class for mock connector configurable

---

core/docs/changelog/WCM-248.change
core/src/zeit/cms/content/dav.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/interfaces.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/models.py
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_postgresql.py

WCM-248: Use feature_toggles.xml in zeit.connector after move to config repo

---

core/docs/changelog/WCM-285.change
core/src/zeit/connector/converter.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/interfaces.py
core/src/zeit/connector/migrations/postdeploy/20240912_1058-6cc99f5afdc5_add_channels_columns_.py
core/src/zeit/connector/migrations/predeploy/20240912_1056-9aba9394d011_add_channels_columns.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/models.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_postgresql.py

WCM-285: new columns channel and subchannels

---

core/docs/changelog/WCM-291.change
core/src/zeit/cms/content/dav.py
core/src/zeit/connector/converter.py
core/src/zeit/connector/migrations/predeploy/20240918_0829-b7304b8f2b06_add_modified_publish_info_datetime_.py
core/src/zeit/connector/models.py
core/src/zeit/connector/tests/test_postgresql.py

WCM-291: move timestamps into columns

---

core/src/zeit/content/volume/browser/form.py
core/src/zeit/content/volume/browser/resources/volume-covers.js
core/src/zeit/content/volume/interfaces.py

WCM-316: fix alignment of volume and covers and make volume.teaser a large text area

---

core/docs/changelog/WCM-408.change
core/src/zeit/content/volume/volume.py

Fallback-Logik von `volume_note` zu `teaserText` wurde entfernt, da wir alle `teaserText` in der Datenbank bereits zu `volume_note` umbenannt haben (siehe [WCM-408](https://zeit-online.atlassian.net/browse/WCM-408))
[WCM-408]: https://zeit-online.atlassian.net/browse/WCM-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WCM-408: remove fallback logic of teaserText

---

core/docs/changelog/FIX_attach-span-celery.change
core/src/zeit/cms/celery.py

`attach_span` wurde durch `attach_context` ersetzt, siehe Commit:
https://github.com/open-telemetry/opentelemetry-python-contrib/commit/c3e9f75fb9611d1e2842b4f3fe11b910d7d2ae0c#diff-ed0dafdf74eda90912242a368cd05845c26ce3178f34c4fea9816f3ff1e49307R202

FIX: attach_span of opentelemetry fixed

---

core/docs/changelog/WCM-401.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/browser/form.py
core/src/zeit/content/audio/browser/tests/test_form.py
core/src/zeit/content/audio/ftesting.zcml
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/testing.py
core/src/zeit/find/testing.py

Neuer Audio-Objekt-Typ `manual` hinzugefügt und `teaser`-Attribute von `ICommonMetadata` in der Form genutzt.
Ticket: [WCM-401](https://zeit-online.atlassian.net/browse/WCM-401)
[WCM-401]: https://zeit-online.atlassian.net/browse/WCM-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Docs: https://github.com/ZeitOnline/vivi-deployment/pull/1166

WCM-401: add new audio object type 'custom'

---

core/docs/changelog/FIX_manual-audio-publish-not-working.change
core/src/zeit/content/audio/browser/configure.zcml

Das manuelle publishen von `Audio`s hat nicht funktioniert, da eine Klasse fehlte.

FIX: manual audio publish not working

---

core/docs/changelog/WCM-452.change
core/src/zeit/connector/converter.py
core/src/zeit/connector/tests/test_mock.py

Also, das auf Mock-Connector Ebene zu testen produziert exakt den Fehler. So weit, so gut. Allerdings ist es in echt ja mit dem SQL-Connector aufgetreten. Fehlt uns also doch noch irgendwie eine Test/Toggle/irgendwas-Ebene?

WCM-452: Handle empty channels in type conversion

---

core/docs/changelog/tmscontent.fix
core/src/zeit/retresco/content.py

Since we now need tms/json-specific conversion, ITMSContent [no longer falls back](https://github.com/ZeitOnline/zeit.web/actions/runs/11325782035/job/31493386599#step:13:2672) to the normal DAVPropertyConverter to deserialize datetimes, so we need to handle that in the specific one of course.

WCM-434: Apply TMS type conversion for datetime in both directions (belongs to 09bef55)

---

core/docs/changelog/WCM-456.change
core/src/zeit/cms/content/dav.py
core/src/zeit/connector/filesystem.py
core/src/zeit/connector/mock.py
core/src/zeit/connector/models.py
core/src/zeit/connector/testing.py
core/src/zeit/connector/tests/test_contract.py
core/src/zeit/connector/tests/test_mock.py
core/src/zeit/connector/tests/test_postgresql.py

Die API Änderung des DAVPropertyConverters ist das Problem, dass sich durch das Zurückdrehen des `write_metadata_columns` Toggles gezeigt hat. 
Der Toggle hat dafür gesorgt, dass nicht nur die Daten in die neuen Spalten geschrieben werden, sondern auch, dass in den Properties der Resource keine Strings, sondern Python Objekte drin stehen. Beispielsweise `PropertyKey(name='year', namespace='http://namespaces.zeit.de/CMS/document'): 2008` statt `PropertyKey(name='year', namespace='http://namespaces.zeit.de/CMS/document'): '2008'`. Oder `PropertyKey(name='date_created', namespace='http://namespaces.zeit.de/CMS/document'): DateTime(2024, 10, 16, 15, 5, 32, 67016, tzinfo=Timezone('Europe/Berlin'))` statt `PropertyKey(name='date_created', namespace='http://namespaces.zeit.de/CMS/document'): …

WCM-456: Write toggle must not break checkin

---

core/docs/changelog/WCM-445.change
core/src/zeit/connector/migrations/predeploy/20241015_1128-b03c427b88de_wcm_445_gallery_type_column.py
core/src/zeit/connector/models.py

Neue Spalte `gallery_type`, aber kein Index, weil dieser keine Auswirkung auf die Query Performance hätte. Die Spalten sind nun immer in Paketen getoggelt. Die Datenmigration der `gallery_type` Spalte soll zusammen mit den Spalten für Rawqueries erfolgen, siehe [Ticket](https://zeit-online.atlassian.net/browse/WCM-471).

WCM-445: Add gallery_type column and alembic migration

---

core/docs/changelog/FIX_adjust-maintenance-hours-for-vg-wort
core/src/zeit/vgwort/cli.py

Die Timezone `UTC` hat Probleme gemacht. Der Wartungszeitraum von VGWort ist zwischen 03:00 und 06:00 morgens. Wir haben noch 10 Minuten Puffer reingemacht.

FIX: adjust maintenance hours for vg wort and timezone

---

core/docs/changelog/log.fix
core/src/zeit/cms/checkout/manager.py
core/src/zeit/workflow/publish.py

FIX: Bring back variable resolution for error messages in log

---

core/docs/changelog/WCM-507.change
core/src/zeit/find/browser/find.py
core/src/zeit/find/search.py

Das Feld muss natürlich auch im `_source` des elastic Queries enthalten sein 🙄

WCM-507: elastic search returns authors field

---

core/docs/changelog/WCM-471.change
core/src/zeit/connector/migrations/postdeploy/20241111_1359-b6c4f9badee3_wcm_471_raw_query_columns.py
core/src/zeit/connector/migrations/predeploy/20241015_1128-b03c427b88de_wcm_445_gallery_type_column.py
core/src/zeit/connector/migrations/predeploy/20241105_1528-fb15e09b44f8_wcm_471_raw_query_columns.py
core/src/zeit/connector/models.py

Warum ein Index für `article_audio_premium_enabled`? Weil sich die execution time der Query von ca 40 ms auf 10ms verringert hat siehe https://zeit-online.atlassian.net/browse/WCM-471?focusedCommentId=105019 . Bzw mit der herausgesuchten Query https://zeit-online.atlassian.net/browse/WCM-471?focusedCommentId=105018
Warum ist `seo_meta_robots` plötzlich ein Array? Weil die Query meist unter 10ms dauert statt mit `Varchar` Type und `varchar_pattern_ops`-Index 40ms. Und die Zeiten stabiler sind, als bei Varchar.
oder auch, wir sollten das nochmal diskutieren, siehe https://zeit-online.atlassian.net/browse/WCM-471?focusedCommentId=105017
Sowohl für `seo_meta_robots` als Array, als auch als Varchar: wenn man versucht die Ergebnisse nach `date_last_published_semantic` zu ordnen, sind wir für …

WCM-471: Columns for raw queries

---

core/docs/changelog/WCM-520.change
core/src/zeit/connector/postgresql.py
core/src/zeit/connector/tests/test_postgresql.py

This is somewhat insiduous, because the API *sometimes* does what we want even without the explicit parameter.

WCM-520: Fix sqlalchemy API usage error that generated queries like `select count(*) where` without a `from` clause

---

core/docs/changelog/WCM-544.change
core/src/zeit/content/cp/README.txt
core/src/zeit/content/cp/centerpage.py

WCM-544: read centerpage type from properties and not from xml body

---

core/docs/changelog/WCM-551.change
core/src/zeit/cms/content/sources.py

Especially with WCM-462 where each column looks for toggles, this yields a 5% performance improvement (local measurement 7.7s instead of 8.1 for a CP)

WCM-551: Cache analyzed toggles, not just their XML nodes

---

core/docs/changelog/WCM-568.change
core/src/zeit/brightcove/configure.zcml
core/src/zeit/brightcove/json/tests/test_update.py
core/src/zeit/brightcove/json/update.py
core/src/zeit/brightcove/testing.py
core/src/zeit/brightcove/update.py

WCM-568: Ignore brightcove change events that were triggered by our own checkin handler

---

core/docs/changelog/WCM-257.change
core/src/zeit/cms/checkout/helper.py
core/src/zeit/cms/checkout/interfaces.py
core/src/zeit/newsimport/news.py
core/src/zeit/newsimport/tests/test_news.py
core/src/zeit/retresco/testhelper.py

Auf den Verdacht hin, dass wir hier ein ähnliches Cache-Overwrite-Problem mit einem concurrent TMS-Job haben, wie wir mit #769 bei Publish umpflastert haben.

WCM-257: Improve news import handling

---

core/docs/changelog/FIX_publish-script-not-working.change
core/src/zeit/cms/workflow/cli.py

Der Publish-Script hat nicht funktioniert, da `info.date_last_published` `None` sein kann.

FIX: publish script not working when info.date_last_published is None

---

core/docs/changelog/WCM-574.change
core/src/zeit/cms/content/feature-toggle.xml
core/src/zeit/cms/content/sources.py
core/src/zeit/cms/ftesting-securitypolicy.zcml
core/src/zeit/cms/permissions.zcml
core/src/zeit/content/text/browser/configure.zcml
core/src/zeit/content/text/browser/embed.py
core/src/zeit/content/text/browser/tests/test_embed.py
core/src/zeit/content/text/embed.py
core/src/zeit/securitypolicy/security.zcml

Die Rechteanforderung für embeds ist erwünscht

WCM-574: remove toggle add_content_permissions and use new content permissions for embeds

---

core/docs/changelog/newsimport_images.change
core/src/zeit/cms/content/feature-toggle.xml
core/src/zeit/newsimport/news.py
core/src/zeit/newsimport/tests/test_news.py

Bilder können implizit zurückgezogen werden, indem ein Artikel Update ohne `main_image` Entry kommt, oder explizit indem ein reines Image Update kommt. Siehe [Kommentar](https://zeit-online.atlassian.net/browse/ZO-540?focusedCommentId=78012)
Der Code für Delete war in Production nicht aktiv, denn der Toggle wurde nie umgeschmissen. Trotzdem sollten Bilder von der dpa nicht einfach veröffentlicht bleiben, selbst wenn der entsprechende Artikel, der sie referenziert, zurückgezogen wurde. Das lässt befürchten, dass es in prod lauter veröffentlichte dpa-Bilder gibt, die nirgendwo mehr hingehören.

WCM-599: Replace delete by retract for images in newsimport

---

core/docs/changelog/WCM-559.change
core/src/zeit/speech/connection.py
core/src/zeit/speech/errors.py
core/src/zeit/speech/tests/test_connection.py

Die Audioreferenz sollten wir so früh wie möglich an den Artikel hängen. Checkin Checkout Fehler werden einfach nochmal probiert durch Celery. Konsequenz ist natürlich das Artikel mit unveröffentlichten Änderungen händisch durch die Redakteure veröffentlicht werden müssen.
Aber so umgehen wir das ein Audio gar nicht mehr am Artikel ist, weil die erfolgten Änderungen keinen Einfluss auf die TTS Neuerstellung hatten.
Sollte dann auch bei [WCM-186](https://zeit-online.atlassian.net/browse/WCM-186) helfen
[WCM-186]: https://zeit-online.atlassian.net/browse/WCM-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WCM-559: add tts references to articles even if the checksum does not match

---

core/docs/changelog/WCM-533.change
core/src/zeit/content/article/edit/browser/form.py

WCM-533: hide legend for access entitlements if field is not available

---

core/docs/changelog/WCM-195.change
core/src/zeit/cms/tagging/browser/resources/tag.js
core/src/zeit/cms/tagging/browser/tests/test_widget.py
core/src/zeit/cms/tagging/browser/widget.py

Ticket: [WCM-195](https://zeit-online.atlassian.net/browse/WCM-195)
Der Link wird jetzt hinter dem jeweiligen Tag angezeigt, wenn es einen gibt:
[WCM-195]: https://zeit-online.atlassian.net/browse/WCM-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WCM-195: display link next to tag title

---

core/docs/changelog/WCM-195.change
core/src/zeit/cms/browser/resources/cms_widgets.css

[Sonja fiel auf](https://zeit-online.atlassian.net/browse/WCM-195?focusedCommentId=107004), dass Keyword-Texte durch die neuen Links viele Zeilenumbrüche haben und somit mit anderen Keywords überlappen. Das sieht merkwürdig aus. Zum Beispiel beim Keyword `Justizminsterium der Vereinigten Staaten (Organisation)` (damit kann man auf jeden Fall auch gut testen) und ähnlich langen Keywords gibt es Probleme.
In diesem PR wurden alle Keywords durch `text-overflow: ellipsis;` ausgepunktet. Beim Hovern werden sie komplett angezeigt.
Alter Stand:
Neuer Stand (mit Keyword auf Justizministerium der USA):

WCM-195: truncate keywords using ellipsis and show them on hover in full height

---

core/src/zeit/content/article/edit/browser/resources/editor.css
core/src/zeit/edit/browser/resources/editor.css

Ein paar Kleinigkeiten:
- `border-radius` an den Artikel-Formular-Blöcken wird umgedreht (oben keiner, unten schon)
- Zusätzlicher Rahmen zwischen Formular-Kopf und Inhalt kommt weg
- Das Eilmeldung-Zurückziehen-Element reißt keine Lücken mehr in sein Formular
- Das Memo-Eingabefeld oben wird ein bisschen gleichmäßiger positioniert
- Das Seitenverhältnis-Eingabefeld an Bildern bricht responsiv um in schmaleren Fenstern

MAINT: Bit nicer article editor styling

---

core/docs/changelog/WCM-195.change
core/src/zeit/cms/browser/resources/cms_widgets.css

WCM-195: fix keyword widget design

---

core/docs/changelog/legacy_liveblog.maint
core/docs/changelog/liveblog_lsc.fix
core/docs/changelog/liveblog_use_default.fix
core/src/zeit/content/article/edit/browser/configure.zcml
core/src/zeit/content/article/edit/browser/edit.py
core/src/zeit/content/article/edit/browser/tests/test_edit.py
core/src/zeit/content/article/edit/browser/tests/test_liveblog.py
core/src/zeit/content/article/edit/configure.zcml
core/src/zeit/content/article/edit/interfaces.py
core/src/zeit/content/article/edit/liveblog.py
core/src/zeit/content/article/edit/tests/test_liveblog.py
core/src/zeit/content/modules/interfaces.py
core/src/zeit/content/modules/liveblog.py
core/src/zeit/content/modules/testing.py
core/src/zeit/content/modules/tests/fixtures/liveblog-source.xml

Zuerst klaue ich die Tests vom alten Liveblog, die Tickaroo-Liveblogs hatten nämlich noch gar keine Tests. Dabei fällt mir auf, dass zwei Kleinigkeiten fehlen, also versuche ich sie zu fixen. Und am Ende kommt das alte Liveblog weg.

MAINT: Remove legacy liveblog and add small enhancements to tickaroo liveblog

---

core/docs/changelog/WCM-605.change
core/pyproject.toml
core/src/zeit/cms/application.zcml
core/src/zeit/cms/celery.py
core/src/zeit/cms/tests/test_application.py
core/src/zeit/cms/tests/test_tracing.py
core/src/zeit/cms/tracing.py

zusammen mit https://github.com/ZeitOnline/vivi-deployment/pull/1247 mergen

WCM-605: Report server/client duration as seconds instead of ms

---

core/docs/changelog/WCM-649.change

WCM-649: Unregister ZAR interfaces, so they are not used again

---

core/docs/changelog/WCM-749.change
core/pyproject.toml
core/src/zeit/cms/celery.py

DEPLOYMENT_BRANCH=WCM-749-celery-healthcheck
Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/1286

WCM-749: Wire up celery worker healthcheck

---

core/docs/changelog/vgwort.fix
core/src/zeit/retresco/metrics.py

FIX: Called wrong method for vgwort metrics

---

core/docs/changelog/WCM-789.change
core/src/zeit/retresco/update.py

WCM-789: Continue publish if TMS fails, retry it asynchronously

---

core/docs/changelog/wcm-636.change
core/src/zeit/authentication/azure.py
core/src/zeit/authentication/oidc.py
core/src/zeit/authentication/tests/test_azure.py

Stop all the request to AD to figure out, what the users name is 🛑

WCM-636: Use email instead of displayName for principal

---

core/docs/changelog/WCM-736.change
core/src/zeit/cms/tagging/browser/widget.pt
core/src/zeit/cms/tagging/browser/widget.py
core/src/zeit/retresco/testing.py

Benötigt https://github.com/ZeitOnline/vivi-deployment/pull/1307

WCM-736: Adjust keyword widget to separate TMS API and UI URLs

---

core/docs/changelog/WCM-694.change
core/src/zeit/workflow/cli.py

`last_updated` ist auch durch unsere Datenmigrationen nicht viel weniger

WCM-694: remove option to restrict time range in scheduled query because it does not improve performance

---

core/docs/changelog/WCM-694.change
core/src/zeit/workflow/cli.py

The AND condition in retract triggers a bitmap heap scan. Running it will be a bit slower than are regular 5s timeout. Rerunning will eventually be faster cause postgres seems to cache the results, but we do not run the retract cronjob enough to reliable hit that cache situation

WCM-694: add timeout setting for scheduled publish/retract query

---

core/docs/changelog/WCM-694.change
core/src/zeit/workflow/cli.py

Ok, die zeitliche Eingrenzung triggered index scan OHNE das bitmap heap AND

WCM-694: restrict days also for retract timeframe

---

core/docs/changelog/WCM-692.change
core/src/zeit/connector/migrations/postdeploy/20250331_1407-20a7ba9a2def_create_index_for_image_separately_.py
core/src/zeit/connector/migrations/predeploy/20250331_1407-2f7a8b0212ae_add_image_separately_purchased_column.py
core/src/zeit/connector/models.py
core/src/zeit/content/image/browser/imagegroup.py

Basiert auf #1065 wegen alemic Migrationen, den also zuerst mergen.

WCM-692: Switch image purchase report from elasticsearch to content-storage

---

core/docs/changelog/wcm-179.change
core/src/zeit/cms/browser/resources/cms_widgets.css
core/src/zeit/content/cp/browser/resources/editor.css

WCM-179
Das Element für die CP hat nur 80% Breite, der Button ist aber relativ zum Formular (100% Breite) ausgerichtet, also außerhalb des CP-Elements. Der Button wird nur angezeigt, wenn das CP-Element gehovert wird, um zu ihm zu kommen, verlässt der Zeiger das CP-Element aber und der Button verschwindet. Meine Lösung ist, den Button relativ zum CP-Element zu positionieren. Außerdem verschiebe ich ihn ein bisschen und ändere das Styling minimal.

WCM-179: Make sure delete button can be reached

---

core/docs/changelog/WCM-611.change
core/src/zeit/content/volume/browser/tests/test_admin.py
core/src/zeit/content/volume/volume.py

unsere Elastic Query für die heutige Ausgabe sieht so aus:
```
{"query": 
{"bool": 
{"filter": 
[
{"term": {"payload.document.year": 2025}}, 
{"term": {"payload.document.volume": 15}}, 
{"bool": {"should": [
{"term": {"payload.workflow.product-id": "ZEI"}}, 
{"term": {"payload.workflow.product-id": "ZMLB"}}, 
{"term": {"payload.workflow.product-id": "ZECH"}}, 
{"term": {"payload.workflow.product-id": "ZEOE"}}, 
{"term": {"payload.workflow.product-id": "ZESA"}}, 
{"term": {"payload.workflow.product-id": "ZEIH"}}, 
{"term": {"payload.workflow.product-id": "ZBGE"}}, 
{"term": {"payload.workflow.product-id": "ZBGO"}}, 
{"term": {"payload.workflow.product-id": "ZBL"}}, 
{"term": {"payload.workflow.product-id": "ZBKS"}}, 
{"term": {"payload.workflow.product-id": "ZBR"}}, 
{"term": …
```

WCM-611: Fetch volume content from content-storage

---

core/docs/changelog/WCM-831.change
core/src/zeit/cms/checkout/tests/test_webhook.py
core/src/zeit/cms/checkout/webhook.py

Dieser PR erlaubt es, in den Webhooks zusätzlich nach Print-Ressorts zu filtern. Es gibt die Möglichkeit, ein Sternchen zu setzen: In diesem Fall wird geprüft, ob `print_ressort` an der jeweiligen Ressource existiert.

WCM-831: add print ressort filtering for webhooks

---

core/docs/changelog/WCM-888.change
core/src/zeit/cms/metrics.py

Darauf könnten wir einen Alarm der Art `vivi_vgwort_unreported_total > 0` ansetzen.

WCM-888: Add metric to count unreported but reportable vgwort content

---

core/src/zeit/sourcepoint/configure.zcml
core/src/zeit/sourcepoint/connection.py
core/src/zeit/sourcepoint/testing.py

Um in `zeit.web` bequem die aktuellste Datei zu finden, könnten wir der Sauberkeit halber eine Utility benutzen.
DEPLOYMENT_BRANCH=es-172_kilkaya_teaser_splittests

ES-172: Add utility for kilkaya-teaser-splittests

---

core/docs/changelog/wcm-928.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/tests/test_article.py

WCM-928: only add automated categories within the first checkin

---

core/docs/changelog/wcm-901.change
core/src/zeit/content/image/tests/test_transform.py
core/src/zeit/content/image/transform.py

IPTC und Exif sind Standards von gestern und XMP enthält diese Metainformationen.

WCM-901: keep XMP metadata of image when resizing it

---

core/docs/changelog/wcm-950.change
core/src/zeit/content/audio/audio.py
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/test_audio.py

Für das Thumbnail im Feed möchte ich das Bild sowohl vom Audio als auch vom Podcast Objekt holen können

WCM-950: get podcast image cover directly from podcast object same way as audio object

---

core/docs/changelog/WCM-973_meta_title_filename.change
core/src/zeit/content/image/browser/imageupload.py
core/src/zeit/content/image/browser/tests/test_imageupload.py

[WCM-973](https://zeit-online.atlassian.net/browse/WCM-973)
Jetzt gibt es automatisch eine Fehler wenn das Feld leer bleibt (das muss noch ne schöne Fehlermeldung werden).
[WCM-973]: https://zeit-online.atlassian.net/browse/WCM-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WCM-973: Use title from metadata for filename in @@edit-images

---

core/docs/changelog/ENG-232.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py
core/src/zeit/workflow/tests/test_retract_3rdparty.py

Dieser PR fügt das third-party Ziel "followings" hinzu. Dabei soll bei jeder neuen Podcast-Folge ein `post` zu den `merkl`-Followings durchgeführt werden. Ein `delete` soll beim `retracten` geschehen. Bei Artikeln wird hier geprüft, ob sie einen Podcast haben. Wenn ja, werden sie gepublished
https://github.com/ZeitOnline/publisher/pull/646

ENG-232: add publish on new podcast series

---

core/docs/changelog/wcm-999.change
core/src/zeit/content/article/article.py
core/src/zeit/content/article/tests/test_article.py

WCM-999: premium audio does not change article header automatically to podcast

---

core/docs/changelog/ES-275.change
core/src/zeit/content/audio/interfaces.py
core/src/zeit/content/audio/tests/fixtures/podcasts.xml
core/src/zeit/content/audio/tests/test_audio.py

Ticket: https://zeit-online.atlassian.net/browse/ES-275
Ermöglicht zwei neue Attribute an Podcast-Objekten in der `podcasts.xml`:
- `release_frequency` – optionales Freitextfeld für die Erscheinungsfrequenz eines Podcasts (kann aber auch z.B. "Dokupodcast in 8 Episoden" sein, das ist gewollt und okay)
- `contact_email` – optionales Freitextfeld für eine Kontakt-Email der Podcastmacher:innen (keine Validierung der Email)
✅  Wording der Attribute ist auch von der Redaktion bestätigt.
Ursprünglich war auch noch ein Attribut `genres` angedacht, das soll aber komplexer ausgestaltet werden als nur eine einfache String-Liste, daher lassen wir das bis zur Implementierung eines Podcast-Contentobjekts außen vor.

ES-275: Add release_frequency & contact_email attributes to Podcast

---

core/src/zeit/content/article/tests/test_article.py
core/src/zeit/content/audio/browser/tests/test_audio.py
core/src/zeit/content/audio/browser/tests/test_audioupdate.py
core/src/zeit/content/audio/testing.py
core/src/zeit/content/audio/tests/test_audio.py
core/src/zeit/entitlements/tests/test_entitlements.py
core/src/zeit/mediaservice/tests/test_mediaservice.py
core/src/zeit/retresco/tests/test_content.py
core/src/zeit/retresco/tests/test_convert.py
core/src/zeit/speech/tests/test_connection.py

Keep audio tests somehow consistent beyond the different type of audio tests

MAINT: use AudioBuilder for audio tests

---

core/docs/changelog/WCM-1070_normalize_filenames.change
core/src/zeit/content/image/browser/imageupload.edit-images.pt
core/src/zeit/content/image/browser/imageupload.py
core/src/zeit/content/image/browser/tests/test_imageupload.py

Da ist ein kleines Refactoring drin (Umbenennung von `cur_name` zu `tmp_name` und `name` zu `target_name`), und die Normalisierung zieht ein paar Änderungen in den Tests nach sich. Also besser commitweise angucken.

WCM-1070: Normalize target file names in new image upload

---

core/docs/changelog/WCM-1056.change
core/src/zeit/mediaservice/configure.zcml
core/src/zeit/mediaservice/connection.py
core/src/zeit/mediaservice/ftesting.zcml
core/src/zeit/mediaservice/interfaces.py
core/src/zeit/mediaservice/mock_connection.py
core/src/zeit/mediaservice/testing.py
core/src/zeit/mediaservice/tests/test_connection.py

WCM-1056: medienservice preview feed with authentication

---

core/docs/changelog/ENG-344.change
core/src/zeit/workflow/publish_3rdparty.py
core/src/zeit/workflow/tests/test_publish_3rdparty.py

Ticket: [ENG-344](https://zeit-online.atlassian.net/browse/ENG-344)
Dieser PR (der letzte der Following-Reihe), fügt zu `series` und `podcast` auch noch Author hinzu. Da eine Serie mehrere Autoren haben kann, und die `parent_uuid` sowohl auf Autoren als auch Serien zutrifft, wird sie nun als Array gesendet. Daher muss der Publisher auch nochmal kurz angepasst werden.
[ENG-344]: https://zeit-online.atlassian.net/browse/ENG-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
`bin/test -k test_followings_`

ENG-344: add`author` to followings

---

core/src/zeit/addcentral/testing.py
core/src/zeit/authentication/testing.py
core/src/zeit/brightcove/testing.py
core/src/zeit/brightcove/tests/test_convert.py
core/src/zeit/brightcove/tests/test_resolve.py
core/src/zeit/brightcove/tests/test_update.py
core/src/zeit/cmp/testing.py
core/src/zeit/crop/testing.py
core/src/zeit/push/browser/tests/test_form.py
core/src/zeit/push/testing.py
core/src/zeit/push/tests/test_banner.py
core/src/zeit/push/tests/test_urbanairship.py

WCM-1097: vivi-Pakete Tests auf SQL-Connector umstellen
